# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haYrsm4XykJP76iFXzyoPVMG6PnkUxGE
"""

#!pip install pdfplumber
#!pip install streamlit
#!pip install sentence-transformers
#!pip install datasets
#!pip uninstall pillow -y
#!pip install pillow==10.4.0

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from numpy.linalg import norm

from sentence_transformers import SentenceTransformer

from datasets import load_dataset

import pdfplumber

import re
import pickle
import os
from collections import Counter
from typing import List, Tuple

#import nltk
#from nltk.corpus import stopwords
#nltk.download('stopwords', quiet=True)

import streamlit as st

# EDA (Runs only in Colab, not on Streamlit)

def run_eda():

    # LOAD DATA
    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"\nDataset size: {len(df)} samples")
    print(f"Columns: {df.columns.tolist()}")

    # BASIC INFORMATION
    print(f"\nData types:")
    print(df.dtypes)

    print("\nFirst 2 rows preview:")
    print(df.head(2))

    # MISSING VALUES
    missing_counts = df.isnull().sum()
    print(missing_counts)

    if missing_counts.sum() == 0:
        print("No missing values found")

    # CLASS DISTRIBUTION
    class_counts = df['label'].value_counts()
    print(f"\nClass distribution:\n{class_counts}")

    # PLOT
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ['#e74c3c', '#f39c12', '#2ecc71']
    class_counts.plot(kind='bar', ax=ax, color=colors)
    ax.set_title('Class Distribution (Fit Labels)', fontsize=14)
    ax.set_xlabel('Fit Category')
    ax.set_ylabel('Count')
    ax.set_xticklabels(class_counts.index, rotation=45)

    total = class_counts.sum()
    for i, v in enumerate(class_counts.values):
        ax.text(i, v + 5, f'{v/total*100:.1f}%', ha='center', fontsize=11)

    plt.tight_layout()
    plt.savefig('class_distribution.png', dpi=150)
    plt.show()

    # TEXT LENGTH ANALYSIS
    df['text_length'] = df['text'].astype(str).str.len()
    df['text_words'] = df['text'].astype(str).str.split().str.len()

    print(f"\nText length (characters):")
    print(f"  Min: {df['text_length'].min():,}")
    print(f"  Max: {df['text_length'].max():,}")
    print(f"  Mean: {df['text_length'].mean():,.0f}")
    print(f"  Median: {df['text_length'].median():,.0f}")

    print(f"\nText length (words):")
    print(f"  Min: {df['text_words'].min():,}")
    print(f"  Max: {df['text_words'].max():,}")
    print(f"  Mean: {df['text_words'].mean():,.0f}")
    print(f"  Median: {df['text_words'].median():,.0f}")

    # TEXT LENGTH PLOTS
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].hist(df['text_words'], bins=50, color='#3498db', alpha=0.7, edgecolor='black')
    axes[0].axvline(df['text_words'].median(), color='red', linestyle='--', label=f"Median: {df['text_words'].median():.0f}")
    axes[0].set_title('Text Length Distribution (Words)', fontsize=12)
    axes[0].set_xlabel('Number of Words')
    axes[0].set_ylabel('Frequency')
    axes[0].legend()

    axes[1].hist(df['text_length'], bins=50, color='#e67e22', alpha=0.7, edgecolor='black')
    axes[1].axvline(df['text_length'].median(), color='red', linestyle='--', label=f"Median: {df['text_length'].median():.0f}")
    axes[1].set_title('Text Length Distribution (Characters)', fontsize=12)
    axes[1].set_xlabel('Number of Characters')
    axes[1].set_ylabel('Frequency')
    axes[1].legend()

    plt.tight_layout()
    plt.savefig('text_length_distributions.png', dpi=150)
    plt.show()

    # SAMPLE TEXT INSPECTION
    print("\nSample text (first 500 chars):")
    print(df['text'].iloc[0][:500] + "...")

    # DUPLICATE CHECKS
    duplicate_count = df.duplicated().sum()
    print(f"Duplicate rows: {duplicate_count}")

    # SUMMARY
    print(f"""
    Dataset Size: {len(df):,} samples
    Classes: {class_counts.index.tolist()}
    Class Distribution: No Fit: {class_counts.get('No Fit', 0)}, Potential Fit: {class_counts.get('Potential Fit', 0)}, Good Fit: {class_counts.get('Good Fit', 0)}
    Missing Values: None
    Average Text Length: {df['text_length'].mean():.0f} characters ({df['text_words'].mean():.0f} words)
    Duplicates: {duplicate_count}

    RECOMMENDATIONS:
    1. No missing values to handle
    2. Class imbalance exists - use stratification in train/test split
    3. Text length varies - ensure model can handle long sequences
    4. Data is ordered by label - shuffle before splitting
    """)

    return df

#Support Functions

# SYNONYM REPLACEMENT: Lower (synonym) → Middle (canonical term)

SYNONYM_TO_CANONICAL = {
    # ===== PROGRAMMING LANGUAGES =====
    'j2se': 'java',
    'java se': 'java',
    'java standard edition': 'java',
    'core java': 'java',
    'java 8': 'java',
    'java 11': 'java',
    'java 17': 'java',
    'java 21': 'java',
    'py': 'python',
    'python3': 'python',
    'python 3': 'python',
    'cpython': 'python',
    'js': 'javascript',
    'ecmascript': 'javascript',
    'es6': 'javascript',
    'es2020': 'javascript',
    'nodejs': 'javascript',
    'node': 'javascript',
    'deno': 'javascript',
    'bun': 'javascript',
    'ts': 'typescript',
    'typed javascript': 'typescript',
    'typescript js': 'typescript',
    'cpp': 'c++',
    'c plus plus': 'c++',
    'cxx': 'c++',
    'cpp17': 'c++',
    'cpp20': 'c++',
    'c sharp': 'c#',
    'csharp': 'c#',
    'dotnet': 'c#',
    'ror': 'ruby',
    'rails': 'ruby',
    'ruby on rails': 'ruby',
    'php7': 'php',
    'php8': 'php',
    'php8.1': 'php',
    'laravel': 'php',
    'codeigniter': 'php',
    'symfony': 'php',
    'wordpress': 'php',
    'swiftui': 'swift',
    'apple swift': 'swift',
    'kt': 'kotlin',
    'kotlin android': 'kotlin',
    'golang': 'go',
    'golang language': 'go',
    'rustlang': 'rust',
    'scala lang': 'scala',
    'r language': 'r',
    'r programming': 'r',
    'rstats': 'r',
    'dart language': 'dart',
    'perl5': 'perl',
    'perl6': 'perl',
    'shell': 'bash',
    'sh': 'bash',
    'shell script': 'bash',
    'bash script': 'bash',
    'zsh': 'bash',
    'zsh script': 'bash',
    'common business oriented language': 'cobol',
    'commercial business oriented language': 'cobol',
    'cobol 85': 'cobol',
    'ibm cobol': 'cobol',
    'formula translating system': 'fortran',
    'fortran iv': 'fortran',
    'fortran 77': 'fortran',
    'fortran 90': 'fortran',
    'list processing': 'lisp',
    'common lisp': 'lisp',
    'scheme': 'lisp',
    'racket': 'lisp',
    'clojure': 'lisp',
    'smalltalk 80': 'smalltalk',
    'squeak': 'smalltalk',
    'pharo': 'smalltalk',
    'object pascal': 'pascal',
    'delphi': 'pascal',
    'pl/i language': 'pl/i',
    'programming language one': 'pl/i',
    'simula 67': 'simula',
    'simula language': 'simula',
    'first oop language': 'simula',
    'ada 83': 'ada',
    'ada 95': 'ada',
    'ada 2012': 'ada',
    'dod language': 'ada',
    'matrix laboratory': 'matlab',
    'matlab programming': 'matlab',

    # ===== FRAMEWORKS =====
    'django framework': 'django',
    'django python': 'django',
    'flask python': 'flask',
    'flask web': 'flask',
    'spring boot': 'spring',
    'spring framework': 'spring',
    'spring mvc': 'spring',
    'spring cloud': 'spring',
    'spring data': 'spring',
    'spring security': 'spring',
    'reactjs': 'react',
    'react.js': 'react',
    'react native': 'react',
    'next.js': 'react',
    'nextjs': 'react',
    'gatsby': 'react',
    'remix': 'react',
    'angularjs': 'angular',
    'angular 2': 'angular',
    'angular 4': 'angular',
    'angular 8': 'angular',
    'angular 15': 'angular',
    'vuejs': 'vue',
    'vue.js': 'vue',
    'nuxt': 'vue',
    'nuxtjs': 'vue',
    'quasar': 'vue',
    'node.js': 'node',
    'express': 'node',
    'expressjs': 'node',
    'fastify': 'node',
    'nestjs': 'node',
    'jquery js': 'jquery',
    'bootstrap css': 'bootstrap',
    'bootstrap framework': 'bootstrap',
    'twbs': 'bootstrap',
    'tailwindcss': 'tailwind',
    'tailwind css': 'tailwind',
    'django rest framework': 'django',
    'jinja2': 'flask',
    'play framework': 'play',
    'play scala': 'play',
    'play java': 'play',
    'dropwizard framework': 'dropwizard',
    'dropwizard java': 'dropwizard',
    'gorilla web toolkit': 'gorilla',
    'gorilla mux': 'gorilla',
    'gorilla framework': 'gorilla',
    'flutter framework': 'flutter',
    'flutter app': 'flutter',
    'dart flutter': 'flutter',

    # ===== CLOUD & DEVOPS =====
    'amazon web services': 'aws',
    'amazon cloud': 'aws',
    'aws cloud': 'aws',
    'amazon ec2': 'ec2',
    'elastic compute cloud': 'ec2',
    'amazon s3': 's3',
    'simple storage service': 's3',
    'aws lambda': 'lambda',
    'serverless lambda': 'lambda',
    'function as a service': 'faas',
    'microsoft azure': 'azure',
    'azure cloud': 'azure',
    'ms azure': 'azure',
    'google cloud': 'gcp',
    'google cloud platform': 'gcp',
    'docker container': 'docker',
    'docker engine': 'docker',
    'dockerfile': 'docker',
    'docker-compose': 'docker',
    'docker hub': 'docker',
    'containerization': 'docker',
    'k8s': 'kubernetes',
    'kube': 'kubernetes',
    'kubectl': 'kubernetes',
    'eks': 'kubernetes',
    'aks': 'kubernetes',
    'gke': 'kubernetes',
    'openshift': 'kubernetes',
    'container orchestration': 'kubernetes',
    'jenkins ci': 'jenkins',
    'jenkins pipeline': 'jenkins',
    'jenkinsfile': 'jenkins',
    'ci/cd': 'jenkins',
    'continuous integration': 'jenkins',
    'tf': 'terraform',
    'hashicorp terraform': 'terraform',
    'tf plan': 'terraform',
    'tf apply': 'terraform',
    'iac': 'terraform',
    'infrastructure as code': 'terraform',
    'ansible automation': 'ansible',
    'ansible playbook': 'ansible',
    'ansible tower': 'ansible',
    'configuration management': 'ansible',
    'git scm': 'git',
    'git version control': 'git',
    'git repo': 'git',
    'source control': 'git',
    'vcs': 'git',
    'version control': 'git',
    'gh': 'github',
    'github actions': 'github',
    'github copilot': 'github',
    'github codespaces': 'github',
    'gitlab ci': 'gitlab',
    'gitlab pipeline': 'gitlab',
    'gitlab runner': 'gitlab',
    'gitlab yaml': 'gitlab',
    'bitbucket pipelines': 'bitbucket',
    'bitbucket cloud': 'bitbucket',
    'argo cd': 'argo',
    'argo rollouts': 'argo',
    'gitops': 'argo',
    'prometheus monitoring': 'prometheus',
    'metrics': 'prometheus',
    'monitoring': 'prometheus',
    'grafana dashboard': 'grafana',
    'visualization': 'grafana',
    'observability': 'grafana',
    'elasticsearch': 'elk',
    'logstash': 'elk',
    'kibana': 'elk',
    'elastic stack': 'elk',
    'elasticsearch stack': 'elk',
    'elastic cloud': 'elk',
    'sre': 'devops',
    'site reliability engineering': 'devops',
    'site reliability': 'devops',
    'devsecops': 'devops',
    'mlops': 'devops',
    'aiops': 'devops',
    'cio': 'devops',
    'cto': 'devops',
    'vp engineering': 'devops',

    # ===== DATABASES =====
    'mysql db': 'mysql',
    'maria db': 'mysql',
    'mariadb': 'mysql',
    'percona': 'mysql',
    'postgres': 'postgresql',
    'psql': 'postgresql',
    'pg': 'postgresql',
    'mongo': 'mongodb',
    'nosql': 'mongodb',
    'no sql': 'mongodb',
    'document db': 'mongodb',
    'mongodb atlas': 'mongodb',
    'redis cache': 'redis',
    'in-memory db': 'redis',
    'redis stack': 'redis',
    'redislabs': 'redis',
    'es': 'elasticsearch',
    'elastic': 'elasticsearch',
    'cassandra db': 'cassandra',
    'apache spark': 'spark',
    'pyspark': 'spark',
    'spark sql': 'spark',
    'spark streaming': 'spark',
    'hdfs': 'hadoop',
    'apache hadoop': 'hadoop',
    'yarn': 'hadoop',
    'mapreduce': 'hadoop',
    'apache kafka': 'kafka',
    'confluent kafka': 'kafka',
    'kafka streams': 'kafka',
    'apache airflow': 'airflow',
    'airflow pipeline': 'airflow',
    'dag': 'airflow',
    'data orchestration': 'airflow',
    'snowflake db': 'snowflake',
    'snowflake data cloud': 'snowflake',
    'snowflake warehouse': 'snowflake',
    'databricks lakehouse': 'databricks',
    'dbx': 'databricks',
    'delta lake': 'databricks',
    'aws dynamodb': 'dynamodb',
    'key-value store': 'dynamodb',
    'google bigquery': 'bigquery',
    'gcp bigquery': 'bigquery',
    'serverless data warehouse': 'bigquery',
    'aws redshift': 'redshift',
    'amazon redshift': 'redshift',
    'data warehouse': 'redshift',
    'clickhouse db': 'clickhouse',
    'columnar db': 'clickhouse',
    'olap': 'clickhouse',
    'neo4j graph': 'neo4j',
    'graph database': 'neo4j',
    'cypher': 'neo4j',
    'etl': 'etl',
    'extract transform load': 'etl',
    'elt': 'etl',
    'extract load transform': 'etl',
    'data pipeline': 'etl',
    'data ingestion': 'etl',
    'data integration': 'etl',

    # ===== AI/ML =====
    'ml': 'machine learning',
    'ml engineer': 'machine learning',
    'ml model': 'machine learning',
    'dl': 'deep learning',
    'deep neural network': 'deep learning',
    'dnn': 'deep learning',
    'deep learning model': 'deep learning',
    'nlp': 'nlp',
    'natural language understanding': 'nlp',
    'nlu': 'nlp',
    'text mining': 'nlp',
    'cv': 'computer vision',
    'vision ai': 'computer vision',
    'image recognition': 'computer vision',
    'object detection': 'computer vision',
    'image segmentation': 'computer vision',
    'llm': 'llm',
    'large language model': 'llm',
    'foundation model': 'llm',
    'gpt': 'llm',
    'bert': 'llm',
    'llama': 'llm',
    'gemini': 'llm',
    'claude': 'llm',
    'mistral': 'llm',
    'retrieval augmented generation': 'rag',
    'retrieval-augmented generation': 'rag',
    'vector search': 'rag',
    'transformer model': 'transformers',
    'attention model': 'transformers',
    'self-attention': 'transformers',
    'encoder decoder': 'transformers',
    'convolutional neural network': 'cnn',
    'convnet': 'cnn',
    'recurrent neural network': 'rnn',
    'lstm': 'rnn',
    'gru': 'rnn',
    'bidirectional rnn': 'rnn',
    'bidirectional encoder': 'bert',
    'bert model': 'bert',
    'roberta': 'bert',
    'distilbert': 'bert',
    'generative pre-trained transformer': 'gpt',
    'gpt-3': 'gpt',
    'gpt-4': 'gpt',
    'openai gpt': 'gpt',
    'chatgpt': 'gpt',
    'tf': 'tensorflow',
    'tensorflow 2': 'tensorflow',
    'tf2': 'tensorflow',
    'tensorflow serving': 'tensorflow',
    'tensorflow hub': 'tensorflow',
    'torch': 'pytorch',
    'pytorch lightning': 'pytorch',
    'sklearn': 'scikit-learn',
    'scikit': 'scikit-learn',
    'pandas python': 'pandas',
    'pd': 'pandas',
    'pandas dataframe': 'pandas',
    'np': 'numpy',
    'num py': 'numpy',
    'numpy array': 'numpy',
    'ai/ml': 'mlops',
    'jupyter notebook': 'jupyter',
    'ipynb': 'jupyter',
    'jupyter lab': 'jupyter',
    'colab': 'jupyter',
    'google colab': 'jupyter',
    'huggingface': 'huggingface',
    'hf': 'huggingface',
    'hugging face': 'huggingface',
    'transformers library': 'huggingface',
    'genai': 'genai',
    'generative ai': 'genai',
    'generative artificial intelligence': 'genai',
    'ai generation': 'genai',
    'prompt design': 'prompt engineering',
    'llm prompting': 'prompt engineering',
    'mpl': 'matplotlib',
    'plt': 'matplotlib',
    'pyplot': 'matplotlib',
    'sns': 'seaborn',
    'seaborn plot': 'seaborn',
    'kaggle dataset': 'kaggle',
    'kaggle competition': 'kaggle',
    'kaggle notebook': 'kaggle',

    # ===== BUSINESS =====
    'pm': 'product manager',
    'product management': 'product manager',
    'technical product manager': 'product manager',
    'tpm': 'product manager',
    'product owner': 'product manager',
    'program manager': 'project manager',
    'pgm': 'project manager',
    'agile scrum': 'scrum master',
    'scrum facilitator': 'scrum master',
    'agile coach': 'scrum master',
    'agile methodology': 'agile',
    'agile development': 'agile',
    'safe': 'agile',
    'xp': 'agile',
    'extreme programming': 'agile',
    'adaptive software development': 'agile',
    'kanban board': 'kanban',
    'kanban methodology': 'kanban',
    'objectives and key results': 'okr',
    'okr framework': 'okr',
    'quarterly goals': 'okr',
    'key performance indicator': 'kpi',
    'key metric': 'kpi',
    'performance metric': 'kpi',
    '6 sigma': 'six sigma',
    'lean six sigma': 'six sigma',
    'lean management': 'lean',
    'lean enterprise': 'lean',
    'lean thinking': 'lean',
    'lean manufacturing': 'lean',
    'lean operations': 'lean',
    'muda': 'lean',
    'waterfall methodology': 'waterfall',
    'traditional development': 'waterfall',
    'sequential development': 'waterfall',
    'v-model': 'waterfall',
    'sdlc': 'waterfall',
    'business analyst': 'ba',
    'business analysis': 'ba',
    'requirements gathering': 'ba',
    'return on investment': 'roi',
    'return of investment': 'roi',
    'earnings before interest taxes depreciation amortization': 'ebitda',
    'profit and loss': 'p&l',
    'income statement': 'p&l',
    'profit loss': 'p&l',
    'capital expenditure': 'capex',
    'capital investment': 'capex',
    'operational expenditure': 'opex',
    'operating expense': 'opex',
    'mergers and acquisitions': 'm&a',
    'acquisitions': 'm&a',
    'mergers': 'm&a',
    'due diligence': 'm&a',
    'initial public offering': 'ipo',
    'public offering': 'ipo',
    'ipo launch': 'ipo',
    'private equity firm': 'pe',
    'pe investment': 'pe',
    'venture capitalist': 'vc',
    'vc funding': 'vc',
    'regulatory compliance': 'compliance',
    'legal compliance': 'compliance',
    'audit': 'compliance',
    'risk assessment': 'risk management',
    'risk mitigation': 'risk management',
    'risk framework': 'risk management',
    'enterprise risk management': 'risk management',
    'erm': 'risk management',
    'corporate governance': 'governance',
    'it governance': 'governance',
    'data governance': 'governance',
    'itil': 'governance',
    'organizational change': 'change management',
    'transformation': 'change management',
    'change enablement': 'change management',

    # ===== SOFT SKILLS =====
    'led': 'leadership',
    'lead': 'leadership',
    'head': 'leadership',
    'direct': 'leadership',
    'oversee': 'leadership',
    'managed': 'leadership',
    'managed team': 'leadership',
    'communicate': 'communication',
    'written communication': 'communication',
    'verbal communication': 'communication',
    'presentation': 'communication',
    'storytelling': 'communication',
    'analytical': 'problem solving',
    'critical thinking': 'problem solving',
    'troubleshooting': 'problem solving',
    'decision making': 'problem solving',
    'collaborate': 'collaboration',
    'teamwork': 'collaboration',
    'cross-functional': 'collaboration',
    'cross-team': 'collaboration',
    'adapt': 'adaptability',
    'flexible': 'adaptability',
    'resilient': 'adaptability',
    'change-ready': 'adaptability',
    'prioritization': 'time management',
    'deadline': 'time management',
    'time tracking': 'time management',
    'project timeline': 'time management',
    'negotiate': 'negotiation',
    'vendor negotiation': 'negotiation',
    'contract negotiation': 'negotiation',
    'eq': 'emotional intelligence',
    'empathy': 'emotional intelligence',
    'self-awareness': 'emotional intelligence',
    'interpersonal skills': 'emotional intelligence',
    'strategic planning': 'strategic thinking',
    'long-term strategy': 'strategic thinking',
    'vision': 'strategic thinking',
    'innovative': 'innovation',
    'creative': 'innovation',
    'disruptive': 'innovation',
    'design thinking': 'innovation',
    'customer centric': 'customer focus',
    'user experience': 'customer focus',
    'ux': 'customer focus',
    'customer service': 'customer focus',
    'customer success': 'customer focus',

    # ===== CERTIFICATIONS =====
    'bachelor of science': 'bachelor',
    'bs': 'bachelor',
    'btech': 'bachelor',
    'be': 'bachelor',
    'bcom': 'bachelor',
    'ba': 'bachelor',
    'bsc': 'bachelor',
    'beng': 'bachelor',
    'master of science': 'master',
    'ms': 'master',
    'mtech': 'master',
    'me': 'master',
    'ma': 'master',
    'msc': 'master',
    'meng': 'master',
    'doctorate': 'phd',
    'doctoral': 'phd',
    'dphil': 'phd',
    'dsc': 'phd',
    'master of business administration': 'mba',
    'aws certification': 'aws certified',
    'aws cloud practitioner': 'aws certified',
    'aws solutions architect': 'aws certified',
    'aws developer': 'aws certified',
    'aws sysops': 'aws certified',
    'project management professional': 'pmp',
    'pm certification': 'pmp',
    'chartered financial analyst': 'cfa',
    'certified public accountant': 'cpa',
    'scrum master': 'scrum certified',
    'psm': 'scrum certified',
    'csm': 'scrum certified',
    'scrum certificate': 'scrum certified',
    'it service management': 'itil',
    'itil foundation': 'itil',
    'itil certified': 'itil',
    'certified information security manager': 'cism',
    'security management': 'cism',
    'certified information systems security professional': 'cissp',
    'security certification': 'cissp',
    'certified ethical hacker': 'ceh',
    'ethical hacking certification': 'ceh',
    'offensive security certified professional': 'oscp',
    'penetration testing': 'oscp',
    'azure certification': 'azure certified',
    'azure administrator': 'azure certified',
    'azure developer': 'azure certified',
    'azure architect': 'azure certified',
    'google cloud certification': 'gcp certified',
    'google cloud engineer': 'gcp certified',
    'google cloud architect': 'gcp certified',

    # ===== CYBERSECURITY =====
    'network firewall': 'firewall',
    'next-gen firewall': 'firewall',
    'ngfw': 'firewall',
    'web application firewall': 'firewall',
    'waf': 'firewall',
    'virtual private network': 'vpn',
    'vpn tunnel': 'vpn',
    'site-to-site vpn': 'vpn',
    'intrusion detection system': 'ids',
    'network ids': 'ids',
    'host ids': 'ids',
    'nids': 'ids',
    'hids': 'ids',
    'intrusion prevention system': 'ips',
    'network ips': 'ips',
    'host ips': 'ips',
    'nips': 'ips',
    'hips': 'ips',
    'security information event management': 'siem',
    'splunk': 'siem',
    'qradar': 'siem',
    'logrhythm': 'siem',
    'security operations center': 'soc',
    'soc team': 'soc',
    'security monitoring': 'soc',
    'identity and access management': 'iam',
    'access control': 'iam',
    'privileged access': 'iam',
    'pam': 'iam',
    'multi factor authentication': 'mfa',
    'two factor authentication': 'mfa',
    '2fa': 'mfa',
    'authenticator': 'mfa',
    'single sign-on': 'sso',
    'saml': 'sso',
    'oidc': 'sso',
    'oauth': 'sso',
    'domain name system': 'dns',
    'dns server': 'dns',
    'dns resolution': 'dns',
    'secure sockets layer': 'ssl',
    'tls': 'ssl',
    'transport layer security': 'ssl',
    'https': 'ssl',
    'certificate': 'ssl',
    'public key infrastructure': 'pki',
    'digital certificate': 'pki',
    'ca': 'pki',
    'certificate authority': 'pki',
    'extended detection response': 'xdr',
    'endpoint detection': 'xdr',
    'edr': 'xdr',
    'data loss prevention': 'dlp',
    'data leakage prevention': 'dlp',
    'cloud access security broker': 'casb',
    'cloud security': 'casb',
    'zero trust architecture': 'zero trust',
    'zta': 'zero trust',
    'never trust always verify': 'zero trust',
    'zero trust model': 'zero trust',
    'nist zero trust': 'zero trust',

    # ===== LEGAL =====
    'general data protection regulation': 'gdpr',
    'eu privacy law': 'gdpr',
    'data protection regulation': 'gdpr',
    'dsgvo': 'gdpr',
    'california consumer privacy act': 'ccpa',
    'cpra': 'ccpa',
    'california privacy law': 'ccpa',
    'intellectual property': 'ip',
    'copyright': 'ip',
    'trademark': 'ip',
    'patent': 'ip',
    'trade secret': 'ip',
    'non-disclosure agreement': 'nda',
    'confidentiality agreement': 'nda',
    'non-disclosure': 'nda',
    'master services agreement': 'msa',
    'services agreement': 'msa',
    'statement of work': 'sow',
    'scope of work': 'sow',
    'work order': 'sow',
    'end user license agreement': 'eula',
    'software license': 'eula',
    'license agreement': 'eula',
    'health insurance portability accountability act': 'hipaa',
    'healthcare privacy': 'hipaa',
    'medical data': 'hipaa',
    'soc 2': 'soc2',
    'security controls': 'soc2',
    'audit report': 'soc2',
    'data security': 'soc2',
    'iso 27001': 'iso27001',
    'information security management': 'iso27001',
    'isms': 'iso27001',
    'service level agreement': 'sla',
    'service level': 'sla',
    'sla metrics': 'sla',
    'terms of service': 'tos',
    'terms and conditions': 'tos',
    'terms of use': 'tos',

    # ===== MARKETING =====
    'search engine optimization': 'seo',
    'organic search': 'seo',
    'on-page seo': 'seo',
    'off-page seo': 'seo',
    'search engine marketing': 'sem',
    'paid search': 'sem',
    'pay per click': 'ppc',
    'google ads': 'ppc',
    'adwords': 'ppc',
    'bing ads': 'ppc',
    'click through rate': 'ctr',
    'click rate': 'ctr',
    'cost per acquisition': 'cpa',
    'customer acquisition cost': 'cpa',
    'cac': 'cpa',
    'return on ad spend': 'roas',
    'customer relationship management': 'crm',
    'salesforce': 'crm',
    'hubspot': 'crm',
    'zoho': 'crm',
    'pipedrive': 'crm',
    'email campaign': 'email marketing',
    'newsletter': 'email marketing',
    'marketing automation': 'email marketing',
    'smm': 'social media',
    'social media marketing': 'social media',
    'instagram': 'social media',
    'linkedin': 'social media',
    'twitter': 'social media',
    'facebook': 'social media',
    'tiktok': 'social media',
    'content strategy': 'content marketing',
    'blogging': 'content marketing',
    'thought leadership': 'content marketing',
    'growth marketing': 'growth hacking',
    'growth strategies': 'growth hacking',
    'experimentation': 'growth hacking',
    'brand awareness': 'branding',
    'brand identity': 'branding',
    'brand strategy': 'branding',
    'lead gen': 'lead generation',
    'prospecting': 'lead generation',
    'outreach': 'lead generation',
    'cold outreach': 'lead generation',
    'business to business': 'b2b',
    'enterprise sales': 'b2b',
    'business to consumer': 'b2c',
    'consumer sales': 'b2c',

    # ===== SUPPLY CHAIN =====
    'stock keeping unit': 'sku',
    'product code': 'sku',
    'inventory code': 'sku',
    'upc': 'sku',
    'bill of materials': 'bom',
    'material list': 'bom',
    'parts list': 'bom',
    'warehouse management system': 'wms',
    'transportation management system': 'tms',
    'enterprise resource planning': 'erp',
    'sap': 'erp',
    'oracle': 'erp',
    'microsoft dynamics': 'erp',
    'infor': 'erp',
    'just-in-time': 'jit',
    'third-party logistics': '3pl',
    'fourth party logistics': '4pl',
    'lead logistics provider': '4pl',
    'e-commerce': 'ecommerce',
    'online retail': 'ecommerce',
    'digital commerce': 'ecommerce',
    'shopify': 'ecommerce',
    'magento': 'ecommerce',
    'woocommerce': 'ecommerce',
    'bigcommerce': 'ecommerce',
    'direct to consumer': 'd2c',
    'dtc': 'd2c',
    'direct-to-consumer': 'd2c',
    'omnichannel': 'omni channel',
    'multichannel': 'omni channel',
    'cross-channel': 'omni channel',
    'inventory control': 'inventory management',
    'stock management': 'inventory management',
    'inventory optimization': 'inventory management',
    'demand forecasting': 'demand planning',
    'forecasting': 'demand planning',
    'sales forecast': 'demand planning',
    'purchasing': 'procurement',
    'sourcing': 'procurement',
    'strategic sourcing': 'procurement',
    'transportation': 'logistics',
    'shipping': 'logistics',
    'fulfillment': 'logistics',
    'warehousing': 'logistics',

    # ===== JOB TITLES =====
    'dev': 'developer',
    'software developer': 'developer',
    'software engineer': 'developer',
    'engineer': 'developer',
    'programmer': 'developer',
    'coder': 'developer',
    'full stack developer': 'developer',
    'backend developer': 'developer',
    'frontend developer': 'developer',
    'web developer': 'developer',
    'mobile developer': 'developer',
    'ios developer': 'developer',
    'android developer': 'developer',
    'data science': 'data scientist',
    'ds': 'data scientist',
    'ai scientist': 'data scientist',
    'machine learning scientist': 'data scientist',
    'research scientist': 'data scientist',
    'de': 'data engineer',
    'data infrastructure': 'data engineer',
    'data pipeline engineer': 'data engineer',
    'data platform engineer': 'data engineer',
    'devops engineer': 'devops',
    'site reliability engineer': 'devops',
    'sre': 'devops',
    'cloud engineer': 'devops',
    'quality assurance': 'qa',
    'qa engineer': 'qa',
    'software tester': 'qa',
    'test engineer': 'qa',
    'qa analyst': 'qa',
    'sdet': 'qa',
    'product owner': 'product',
    'technical product manager': 'product',
    'product analyst': 'product',
    'marketing manager': 'marketing',
    'digital marketing': 'marketing',
    'growth marketing': 'marketing',
    'marketing director': 'marketing',
    'financial analyst': 'finance',
    'financial manager': 'finance',
    'finance manager': 'finance',
    'controller': 'finance',
    'cfo': 'finance',
    'sales manager': 'sales',
    'sales director': 'sales',
    'account executive': 'sales',
    'business development': 'sales',
    'bd': 'sales',
    'human resources': 'hr',
    'hr manager': 'hr',
    'talent acquisition': 'hr',
    'recruiting': 'hr',
    'people ops': 'hr',
    'management consultant': 'consultant',
    'strategy consultant': 'consultant',
    'advisory': 'consultant',
    'sme': 'consultant',
    'subject matter expert': 'consultant',

    # ===== GLOBAL =====
    'us': 'usa',
    'united states': 'usa',
    'america': 'usa',
    'americas': 'usa',
    'united kingdom': 'uk',
    'britain': 'uk',
    'england': 'uk',
    'gb': 'uk',
    'great britain': 'uk',
    'northern ireland': 'uk',
    'european union': 'eu',
    'europe': 'eu',
    'european': 'eu',
    'asia pacific': 'apac',
    'asia-pacific': 'apac',
    'asia pacific region': 'apac',
    'europe middle east africa': 'emea',
    'emea region': 'emea',
    'latin america': 'latam',
    'south america': 'latam',
    'central america': 'latam',
    'caribbean': 'latam',
    'middle east north africa': 'mena',
    'mena region': 'mena',
    'gulf cooperation council': 'gcc',
    'middle east gcc': 'gcc',
    'worldwide': 'ww',
    'global': 'ww',
    'international': 'ww',
    'global operations': 'ww',
    'north america': 'north america',
    'na': 'north america',
    'us and canada': 'north america',
    'americas north': 'north america',
    'sa': 'south america',
    'european region': 'europe',
    'eu': 'europe',
    'european countries': 'europe',
    'asia': 'asia',
    'asian countries': 'asia',
    'africa': 'africa',
    'middle east': 'africa',
}

def replace_synonyms(text: str) -> str:
    if not text:
        return ""

    text_lower = text.lower()

    sorted_synonyms = sorted(SYNONYM_TO_CANONICAL.keys(), key=len, reverse=True)# Sort by length (longest first) to prevent partial matches. e.g., "java standard edition" should match before "java"

    for synonym in sorted_synonyms:
        if synonym in text_lower:# Replace whole word only (using word boundaries)
            import re
            pattern = r'\b' + re.escape(synonym) + r'\b'
            text_lower = re.sub(pattern, SYNONYM_TO_CANONICAL[synonym], text_lower)

    return text_lower


def clean_text(text: str) -> str:
    if not text:
        return ""# No msg has been added in order to make sure the msg does not end up in extracted words list
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = replace_synonyms(text)
    return text

def extract_pdf_text(pdf_file):# Extracting all texts from PDF
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    return text.strip()


def extract_keywords(text: str, top_n: int = 20) -> list:
    # Hardcoded stopwords (no NLTK needed).Streamlit may create problems.
    stop_words = {
        'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from',
        'has', 'he', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the',
        'to', 'was', 'were', 'will', 'with', 'i', 'you', 'we', 'they',
        'this', 'that', 'these', 'those', 'am', 'do', 'does', 'did',
        'have', 'had', 'having', 'been', 'being', 'would', 'could',
        'should', 'might', 'must', 'my', 'your', 'his', 'her', 'our',
        'their', 'me', 'him', 'us', 'them'
    }

    words = clean_text(text).split()

    keywords = []
    for w in words:
        if w not in stop_words and (len(w) > 2 or w.isdigit()):
            keywords.append(w)

    freq = Counter(keywords)

    return [word for word, _ in freq.most_common(top_n)]


def skill_gap_analysis(jd_text: str, resume_text: str): # Extraction and comparision
    jd_keywords = set(extract_keywords(jd_text, top_n=30))
    resume_keywords = set(extract_keywords(resume_text, top_n=30))
    present = list(resume_keywords.intersection(jd_keywords))
    missing = list(jd_keywords.difference(resume_keywords))
    return present, missing

print("Support function loaded")

#Sentence Bert Model Blueprint (Section 4)
class ResumeJDMatcher:
    def __init__(self):
        self.model = None
        self.resume_embeddings = None
        self.resume_texts = None

    def load_model(self):
        self.model = SentenceTransformer('all-mpnet-base-v2')#all-MiniLM-L6-v2(384 dimensional embedding size is optimum and fast). But for greater accuracy we are using all-mpnet-base-v2 768 dimensional embedding. We can also consider distiluse-base-multilingual (512 dimensional embedding size) or m2v-256-distiluse-base-multilingual-cased-v2 (256 dimensional embedding size)) .
        print("Model loaded.")
        return self.model

    def encode(self, texts):
        if isinstance(texts, str):
            texts = [texts]
        return self.model.encode(texts, convert_to_numpy=True)#Vectors created(Embedding)

    def compute_similarity(self, emb1, emb2):
        from numpy.linalg import norm
        return float(np.dot(emb1, emb2) / (norm(emb1) * norm(emb2)))#Cosine Singlularity

    def save_embeddings(self, resume_texts, filepath="resume_embeddings.pkl"):#Saving Embedding PErmanently
        if self.model is None:
            self.load_model()
        self.resume_texts = resume_texts
        self.resume_embeddings = self.encode(resume_texts)
        with open(filepath, 'wb') as f:
            pickle.dump({'texts': resume_texts, 'embeddings': self.resume_embeddings}, f)
        print(f"Saved {len(resume_texts)} resume embeddings.")

    def load_embeddings(self, filepath="resume_embeddings.pkl"):#Second most important part.Will reduce time each resume is processed
        if os.path.exists(filepath):
            with open(filepath, 'rb') as f:
                data = pickle.load(f)
            self.resume_texts = data['texts']
            self.resume_embeddings = data['embeddings']
            print(f"Loaded {len(self.resume_texts)} resume embeddings.")
            return True
        return False

    def match_jd(self, jd_text, top_k=5):# the Actual function (actual matching process). By default only Top 5 candidates/resumes will be found. Can be changed
        if self.model is None:
            self.load_model()
        if self.resume_embeddings is None:
            raise ValueError("No resume embeddings loaded. Run save_embeddings() first.")# Safety to prevent crashes

        jd_embedding = self.encode(jd_text)[0]# JD Embedding
        # Compare with all resumes
        similarities = []
        for i, resume_emb in enumerate(self.resume_embeddings):
            score = self.compute_similarity(jd_embedding, resume_emb)
            similarities.append((i, score))# Store resume index and its score

        similarities.sort(key=lambda x: x[1], reverse=True)# Sort by score (highest first)

        results = [] # Build results
        for idx, score in similarities[:top_k]:#Variable (top 5)
            results.append({
                'rank': len(results) + 1,
                'match_score': round(score * 100, 2),
                'resume_preview': self.resume_texts[idx][:200] + "..."
            })
        return results

print("Model class loaded")

#BASELINE MODEL: TF-IDF + Logistic Regression (without sampling)
dataset = load_dataset('facehuggerapoorv/resume-jd-match')# Load dataset
df = pd.DataFrame(dataset['train'])
print(f"Dataset size: {len(df)} samples")

print(f"\nAvailable columns: {df.columns.tolist()}")# CHECK COLUMN NAMES

# Clean text
df['clean_text'] = df['text'].apply(clean_text)

# Create vecorizer
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X = vectorizer.fit_transform(df['clean_text'])
y = df['label']

# Train/test split (With stratification)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)#We use stratified splitting so their is similarity between train and test data for proper model evaluaiton. Random splitting would randomly assign data for train and tests cases, which may give inconsistent results even if model is working.

# Train model
baseline_model = LogisticRegression(max_iter=1000)
baseline_model.fit(X_train, y_train)

# Evaluate
y_pred = baseline_model.predict(X_test)
baseline_accuracy = accuracy_score(y_test, y_pred)

print(f"\nBaseline Accuracy: {baseline_accuracy:.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

#BASELINE MODEL: TF-IDF + Logistic Regression (with 500 sampling)
dataset = load_dataset('facehuggerapoorv/resume-jd-match')
df = pd.DataFrame(dataset['train'])
print(f"Dataset size: {len(df)} samples")

print(f"\nAvailable columns: {df.columns.tolist()}")

# Sampling
SAMPLE_SIZE = 500
sample_df = df.sample(n=SAMPLE_SIZE, random_state=42)
print(f"\nUsing {len(sample_df)} samples for BOTH models")

#We could have used startified sampling but it may enforce some patterns into sample which will make model wrong
#fraction = desired_sample_size / total_population
#sample_df = df.groupby('label', group_keys=False).apply(lambda x: x.sample(frac=fraction, random_state=42))

# Clean text on sample
sample_df['clean_text'] = sample_df['text'].apply(clean_text)

# Create Vecorizer on SAMPLE
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X = vectorizer.fit_transform(sample_df['clean_text'])
y = sample_df['label']

# Train/test split (with stratification)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)

# Train
baseline_model = LogisticRegression(max_iter=1000)
baseline_model.fit(X_train, y_train)

# Evaluate
y_pred = baseline_model.predict(X_test)
baseline_accuracy = accuracy_score(y_test, y_pred)

print(f"\nBaseline Accuracy: {baseline_accuracy:.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

#PREFERRED MODEL: Sbert Model (without sampling)
from sklearn.utils import shuffle
import time

dataset = load_dataset('facehuggerapoorv/resume-jd-match')
df = pd.DataFrame(dataset['train'])
print(f"Dataset size: {len(df)} samples")

# Shuffle, data is ordered. Startify does help but better to shuffle.
df = shuffle(df, random_state=42).reset_index(drop=True)

# Parsing JD and Resume
def parse_jd_resume(text):
    jd_pattern = r'For the given job description <<(.*?)>> the resume:'
    resume_pattern = r'the resume: <<(.*?)>>\. The result is,'

    jd_match = re.search(jd_pattern, text, re.DOTALL)
    resume_match = re.search(resume_pattern, text, re.DOTALL)

    jd = jd_match.group(1).strip() if jd_match else ""
    resume = resume_match.group(1).strip() if resume_match else ""

    return jd, resume

start_time = time.time()
df['jd'], df['resume'] = zip(*df['text'].apply(parse_jd_resume))
print(f"Parsing completed in {time.time() - start_time:.2f} seconds")

#Using all data by converting to python list
jds = df['jd'].tolist()
resumes = df['resume'].tolist()
labels = df['label'].tolist()

print(f"Total JD entries: {len(jds)}")
print(f"Total Resume entries: {len(resumes)}")
print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

#Loading SBERT model
start_time = time.time()
model = SentenceTransformer('all-mpnet-base-v2')# or 'all-MiniLM-L6-v2'
print(f"Model loaded in {time.time() - start_time:.2f} seconds")

#Encoding
start_time = time.time()
jd_embeddings = model.encode(jds, convert_to_numpy=True, show_progress_bar=True)
resume_embeddings = model.encode(resumes, convert_to_numpy=True, show_progress_bar=True)
print(f"Embeddings created in {time.time() - start_time:.2f} seconds")

print(f"JD embeddings shape: {jd_embeddings.shape}")
print(f"Resume embeddings shape: {resume_embeddings.shape}")

#Cosine Similarity
from numpy.linalg import norm

sbert_scores = []
for i in range(len(jds)):
    sim = np.dot(jd_embeddings[i], resume_embeddings[i]) / (norm(jd_embeddings[i]) * norm(resume_embeddings[i]))
    sbert_scores.append(sim * 100)

print(f"SBERT Average Match Score: {np.mean(sbert_scores):.2f}%")
print(f"Score Range: {min(sbert_scores):.2f}% - {max(sbert_scores):.2f}%")

# Combine JD and Resume embeddings
concat_embeddings = np.concatenate([jd_embeddings, resume_embeddings], axis=1)
print(f"Concatenated embeddings shape: {concat_embeddings.shape}")

# Split with stratification
X_train, X_test, y_train, y_test = train_test_split( concat_embeddings, labels, test_size=0.2, random_state=42, stratify=labels)
print(f"Training samples: {len(X_train)}")
print(f"Test samples: {len(X_test)}")

# Train classifier
print("\nTraining Logistic Regression...")
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
sbert_acc = accuracy_score(y_test, y_pred)

print(f"SBERT Classification Accuracy: {sbert_acc:.2%}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

#PREFERRED MODEL: Sbert Model (with 500 sampling)
from sklearn.utils import shuffle
import time

dataset = load_dataset('facehuggerapoorv/resume-jd-match')
df = pd.DataFrame(dataset['train'])
print(f"Dataset size: {len(df)} samples")

# Shuffle data
df = shuffle(df, random_state=42).reset_index(drop=True)

# Random Sampling
sample_df = df.sample(n=500, random_state=42)

# Parsing JD and Resume
def parse_jd_resume(text):
    jd_pattern = r'For the given job description <<(.*?)>> the resume:'
    resume_pattern = r'the resume: <<(.*?)>>\. The result is,'

    jd_match = re.search(jd_pattern, text, re.DOTALL)
    resume_match = re.search(resume_pattern, text, re.DOTALL)

    jd = jd_match.group(1).strip() if jd_match else ""
    resume = resume_match.group(1).strip() if resume_match else ""

    return jd, resume

print("\nParsing JD and Resume...")
start_time = time.time()
sample_df['jd'], sample_df['resume'] = zip(*sample_df['text'].apply(parse_jd_resume))
print(f"Parsing completed in {time.time() - start_time:.2f} seconds")

#Using all data by converting to python list
jds = sample_df['jd'].tolist()
resumes = sample_df['resume'].tolist()
labels = sample_df['label'].tolist()

print(f"\nTotal JD entries: {len(jds)}")
print(f"Total Resume entries: {len(resumes)}")
print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

#Loading SBERT model
start_time = time.time()
model = SentenceTransformer('all-mpnet-base-v2')  # or 'all-MiniLM-L6-v2'
print(f"Model loaded in {time.time() - start_time:.2f} seconds")

#Encoding
start_time = time.time()
jd_embeddings = model.encode(jds, convert_to_numpy=True, show_progress_bar=True)
resume_embeddings = model.encode(resumes, convert_to_numpy=True, show_progress_bar=True)
print(f"Embeddings created in {time.time() - start_time:.2f} seconds")

print(f"JD embeddings shape: {jd_embeddings.shape}")
print(f"Resume embeddings shape: {resume_embeddings.shape}")

#Cosine Similarity
sbert_scores = []
for i in range(len(jds)):
    sim = np.dot(jd_embeddings[i], resume_embeddings[i]) / (norm(jd_embeddings[i]) * norm(resume_embeddings[i]))
    sbert_scores.append(sim * 100)

print(f"SBERT Average Match Score: {np.mean(sbert_scores):.2f}%")
print(f"Score Range: {min(sbert_scores):.2f}% - {max(sbert_scores):.2f}%")

# Combine JD and Resume embeddings
concat_embeddings = np.concatenate([jd_embeddings, resume_embeddings], axis=1)
print(f"Concatenated embeddings shape: {concat_embeddings.shape}")

# Split with stratification
X_train, X_test, y_train, y_test = train_test_split( concat_embeddings, labels, test_size=0.2, random_state=42, stratify=labels)
print(f"Training samples: {len(X_train)}")
print(f"Test samples: {len(X_test)}")

# Train classifier
print("\nTraining Logistic Regression...")
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
sbert_acc = accuracy_score(y_test, y_pred)

print(f"SBERT Classification Accuracy: {sbert_acc:.2%}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

#App code
st.set_page_config(
    page_title="Resume-JD Matcher",
    layout="wide"
)

st.title("Resume - Job Description Matcher")
st.write("Upload a resume (PDF) and paste a job description to calculate a match score.")

if 'matcher' not in st.session_state:
    with st.spinner("Loading model..."):
        st.session_state.matcher = ResumeJDMatcher()
        st.session_state.matcher.load_model()
        st.session_state.match_score = None

with st.sidebar:
    st.subheader("Input")

    jd_text = st.text_area(
        "Job Description",
        height=200,
        placeholder="Paste job description here..."
    )

    uploaded_file = st.file_uploader(
        "Upload Resume (PDF)",
        type=["pdf"]
    )

    process_button = st.button("Process and Match")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Job Description Preview")
    if jd_text:
        st.text_area("", jd_text[:500] + ("..." if len(jd_text) > 500 else ""), height=150, disabled=True)
    else:
        st.info("Paste a job description in the sidebar")

with col2:
    st.subheader("Resume Uploaded")
    if uploaded_file:
        st.success("File uploaded: " + uploaded_file.name)
    else:
        st.info("Upload a PDF resume in the sidebar")

if process_button:
    if not jd_text:
        st.error("Please paste a job description")
    elif not uploaded_file:
        st.error("Please upload a resume")
    else:
        with st.spinner("Processing..."):

            resume_text = extract_pdf_text(uploaded_file)

            if not resume_text:
                st.error("Could not extract text from PDF. Please use a text-based PDF.")
                st.stop()

            cleaned_jd = clean_text(jd_text)
            cleaned_resume = clean_text(resume_text)

            jd_embedding = st.session_state.matcher.encode(cleaned_jd)[0]
            resume_embedding = st.session_state.matcher.encode(cleaned_resume)[0]

            similarity = st.session_state.matcher.compute_similarity(jd_embedding, resume_embedding)
            match_score = similarity * 100

            present_skills, missing_skills = skill_gap_analysis(jd_text, resume_text)

            st.session_state.match_score = match_score
            st.session_state.present_skills = present_skills
            st.session_state.missing_skills = missing_skills
            st.session_state.resume_text = resume_text
            st.session_state.jd_text = jd_text

if st.session_state.get('match_score') is not None:

    st.divider()
    st.subheader("Results")

    match_score = st.session_state.match_score

    col_a, col_b, col_c = st.columns([1, 2, 1])

    with col_b:
        st.markdown(f"<h1 style='text-align: center;'>{match_score:.1f}%</h1>", unsafe_allow_html=True)

        if match_score >= 70:
            st.success("Good Fit")
        elif match_score >= 40:
            st.warning("Potential Fit")
        else:
            st.error("Not a Good Fit")

        st.progress(match_score / 100)

    st.subheader("Score Analysis")
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.barh(['Match Score'], [match_score], color='skyblue')
    ax.axvline(x=70, color='green', linestyle='--', label='Good Fit (70%)')
    ax.axvline(x=40, color='orange', linestyle='--', label='Potential Fit (40%)')
    ax.set_xlim(0, 100)
    ax.set_xlabel('Match Score (%)')
    ax.legend()
    st.pyplot(fig)

    st.subheader("Skill Gap Analysis")

    c1, c2 = st.columns(2)

    with c1:
        st.write("Present Skills")
        if st.session_state.present_skills:
            st.write(", ".join(st.session_state.present_skills[:15]))
        else:
            st.caption("No matching skills found")

    with c2:
        st.write("Missing Skills")
        if st.session_state.missing_skills:
            st.write(", ".join(st.session_state.missing_skills[:15]))
        else:
            st.caption("All key skills found")

    with st.expander("Resume Preview"):
        st.text(st.session_state.resume_text[:1500] + "..." if len(st.session_state.resume_text) > 1500 else st.session_state.resume_text)

    with st.expander("Job Description Preview"):
        st.text(st.session_state.jd_text[:1500] + "..." if len(st.session_state.jd_text) > 1500 else st.session_state.jd_text)

st.divider()
st.caption("Built with Sentence-BERT for semantic matching")

"""# Model Evaluation Report

## 1. Executive Summary

The Resume-JD Matching system compares TF-IDF (baseline) and Sentence-BERT (advanced) for matching resumes to job descriptions.

- **Baseline (TF-IDF + Logistic Regression):** 87.59% accuracy
- **Advanced (SBERT + Logistic Regression):** 60.13% accuracy
- **Key Insight:** The dataset is optimized for classification, not matching.

**Recommendation:** The TF-IDF model is highly effective for this dataset. SBERT would perform better with a proper matching dataset (separate resume and JD columns). PArsing MEthod was used to split the dataset still no improvement was detected.

---

## 2. Dataset Overview

- **Dataset:** facehuggerapoorv/resume-jd-match (6,241 samples)
- **Format:** Combined text (JD + Resume) with label
- **Labels:** No Fit (50.3%), Potential Fit (24.9%), Good Fit (24.7%)
- **Average Text Length:** 1,092 words per sample

---

## 3. Evaluation Methodology

- **Split:** 80% training, 20% testing
- **Stratification:** Used to handle class imbalance
- **Shuffling:** Applied to prevent label ordering bias
- **Metrics:** Accuracy, Precision, Recall, F1-Score

---

## 4. Quantitative Results

### Baseline Model (TF-IDF + Logistic Regression)

| Metric | Score |
|--------|-------|
| Accuracy | 87.59% |
| Precision (macro) | 0.89 |
| Recall (macro) | 0.85 |
| F1-Score (macro) | 0.86 |

### Per-Class Performance (TF-IDF)

| Class | Precision | Recall | F1-Score | Support |
|-------|-----------|--------|----------|---------|
| Good Fit | 0.87 | 0.84 | 0.86 | 309 |
| No Fit | 0.85 | 0.97 | 0.91 | 629 |
| Potential Fit | 0.95 | 0.73 | 0.82 | 311 |

### Advanced Model (SBERT + Logistic Regression)

| Metric | Score |
|--------|-------|
| Accuracy | 60.13% |
| Precision (macro) | 0.60 |
| Recall (macro) | 0.55 |
| F1-Score (macro) | 0.56 |

### Per-Class Performance (SBERT)

| Class | Precision | Recall | F1-Score | Support |
|-------|-----------|--------|----------|---------|
| Good Fit | 0.59 | 0.51 | 0.55 | 309 |
| No Fit | 0.61 | 0.76 | 0.67 | 629 |
| Potential Fit | 0.59 | 0.37 | 0.46 | 311 |

---

## 5. Key Findings

| Finding | Explanation |
|---------|-------------|
| **TF-IDF performs excellently** | The dataset has clear keyword patterns that predict labels |
| **SBERT underperforms** | The dataset is artificial (combined text), not suitable for SBERT's semantic matching |
| **Class imbalance impacts recall** | Potential Fit has the lowest recall (0.37 in SBERT, 0.73 in TF-IDF) |

---

## 6. Limitations

1. **Artificial Dataset:** The JD and Resume are combined, not naturally separated
2. **Synthetic Labels:** Labels may be generated, not based on real hiring decisions
3. **Length Constraints:** SBERT's 512-token limit may truncate long texts
4. **Task Mismatch:** SBERT is designed for matching, not classification

---

## 7. Business Usability Assessment

| Criteria | TF-IDF | SBERT | Assessment |
|----------|--------|-------|------------|
| Accuracy | 87.59% | 60.13% | TF-IDF is highly accurate |
| Interpretability | High | Low | TF-IDF is more explainable |
| Latency | Very Fast | Fast | Both are acceptable |
| Usability | Yes | Yes | Both can be deployed |

**Final Verdict:** TF-IDF is the recommended model for this dataset due to its high accuracy and interpretability.

---

## 8. Future Work

1. **Acquire a proper matching dataset** with separate JD and Resume columns
2. **Fine-tune SBERT** on domain-specific data
3. **Create a multi-dimensional synonym map using knowledge graph embeddings** to intelligently handle industry jargon and cross-domain relationships
4. **Deploy to Streamlit Cloud or Hugging Face Spaces** for public access
5. **Add FastAPI endpoint** for programmatic API access
6. **Implement batch processing** to support multiple resume uploads
7. **Add bias detection and fairness audits**
8. **Integrate OCR support** for scanned/image-based PDF resumes
9. **Add section weighting** to prioritize Work Experience over Hobbies

---

## 9. Conclusion

The TF-IDF model achieves 87.59% accuracy on this dataset, significantly outperforming SBERT (60.13%). This is because the dataset is designed for classification, not matching. For proper resume-JD matching, SBERT would be the better choice with a suitable dataset.

#Read Me (file also shared seperately)

# Resume-Job Description Matcher

An AI-powered system that automatically screens resumes against job descriptions using semantic similarity.

## Features

- Upload multiple PDF resumes
- Paste any job description
- Get match scores (0-100%)
- Ranked candidate list
- Skill gap analysis
- Visual score distribution chart

## Tech Stack

- Python 3.9+
- Sentence-BERT (semantic embeddings)
- Streamlit (web interface)
- scikit-learn (baseline model)
- pdfplumber (PDF text extraction)

## Installation

git clone https://github.com/shashwatbudakoti-git/resume-jd-matcher
streamlit run app.py

#PPT (File also shared seperately)
Resume-Job Description Matcher

AI/ML Specialisation Capstone Project
Shashwat Budakoti
21-06-26


---
Problem Statement
- Recruiters spend 10-15 hours per position manually screening resumes
- Manual screening is time-consuming and inconsistent
- Need for automated preliminary screening

Solution
- Build a classifier that predicts resume-JD fit
- Rank candidates by match score
- Identify skill gaps

Target Users
- HR teams, recruiters, career services



---
Dataset
Dataset: facehuggerapoorv/resume-jd-match
Source: Hugging Face Datasets
Size: 6,241 samples
Format: Combined JD + Resume text with label

Labels Distribution:
- No Fit: 3,143 (50.3%)
- Potential Fit: 1,556 (24.9%)
- Good Fit: 1,542 (24.7%)

Average Text Length: 1,092 words



---
Two Methodologies

1. Baseline: TF-IDF + Logistic Regression
   - Converts text to numerical features
   - Simple, interpretable, fast

2. Advanced: Sentence-BERT
   - Semantic understanding
   - Captures meaning beyond keywords
   - Model: all-mpnet-base-v2 (768 dimensions)



---
Comparison

┌─────────────────────────────┬─────────────┐
│ Metric                      │ TF-IDF      │ SBERT    │
├─────────────────────────────┼─────────────┼──────────┤
│ Accuracy                    │ 87.59%      │ 60.13%   │
│ Macro F1                    │ 0.86        │ 0.56     │
│ Processing Time (Full)      │ ~10 sec     │ ~5 min   │
└─────────────────────────────┴─────────────┴──────────┘

TF-IDF outperforms SBERT on this dataset
Dataset is optimized for classification, not matching



---
EDA Insights:

1. No missing values
2. Class imbalance: No Fit is 50.3%
3. Text length: 169 - 3,920 words
4. Data ordered by label → need to shuffle

Recommendations Applied:
- Stratification in train/test split
- Shuffling before splitting
- Truncation for long texts



---
Deployment

Streamlit Web Application

Features:
1. Upload PDF resume
2. Paste job description
3. Get match score (0-100%)
4. Skill gap analysis
5. Candidate ranking

Technology:
- Frontend: Streamlit
- Backend: Python + Sentence-BERT
- Deployment: Local / Streamlit Cloud



---
Conclusion
- TF-IDF achieves 87.59% accuracy
- SBERT achieves 60.13% accuracy
- Dataset is best suited for classification

Limitations:
- Artificial dataset (combined JD + Resume)
- Labels may be synthetic
- SBERT needs proper matching dataset

Future Work:
- Use proper matching dataset
- Fine-tune SBERT on domain data
- Add bias detection
- Deploy to cloud



---

# Requirements
streamlit==1.28.0
sentence-transformers==2.2.2
scikit-learn==1.3.0
pandas==2.0.3
numpy==1.24.3
pdfplumber==0.10.3
torch==2.0.1
datasets==2.14.0
matplotlib==3.7.2
seaborn==0.12.2
"""

# COLAB EXECUTION
if __name__ == "__main__":
    # EDA for collab
    df = run_eda()

    print("Colab execution complete!")