# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHnJxbcZy4-OcgccOjBn2smZYdsxh48X
"""

# -*- coding: utf-8 -*-
"""Capstone.ipynb - Fixed for Streamlit"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import re
import pickle
import os
import time
from collections import Counter
from typing import List, Tuple

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from numpy.linalg import norm
from sklearn.utils import shuffle

from sentence_transformers import SentenceTransformer
from datasets import load_dataset
import pdfplumber

# ============================================================
# EDA FUNCTION (Runs only in Colab)
# ============================================================

def run_eda():
    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"\nDataset size: {len(df)} samples")
    print(f"Columns: {df.columns.tolist()}")
    print(f"\nData types:")
    print(df.dtypes)
    print("\nFirst 2 rows preview:")
    print(df.head(2))

    missing_counts = df.isnull().sum()
    print(missing_counts)
    if missing_counts.sum() == 0:
        print("No missing values found")

    class_counts = df['label'].value_counts()
    print(f"\nClass distribution:\n{class_counts}")

    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ['#e74c3c', '#f39c12', '#2ecc71']
    class_counts.plot(kind='bar', ax=ax, color=colors)
    ax.set_title('Class Distribution (Fit Labels)', fontsize=14)
    ax.set_xlabel('Fit Category')
    ax.set_ylabel('Count')
    ax.set_xticklabels(class_counts.index, rotation=45)

    total = class_counts.sum()
    for i, v in enumerate(class_counts.values):
        ax.text(i, v + 5, f'{v/total*100:.1f}%', ha='center', fontsize=11)

    plt.tight_layout()
    plt.savefig('class_distribution.png', dpi=150)
    plt.show()

    df['text_length'] = df['text'].astype(str).str.len()
    df['text_words'] = df['text'].astype(str).str.split().str.len()

    print(f"\nText length (characters):")
    print(f"  Min: {df['text_length'].min():,}")
    print(f"  Max: {df['text_length'].max():,}")
    print(f"  Mean: {df['text_length'].mean():,.0f}")
    print(f"  Median: {df['text_length'].median():,.0f}")

    print(f"\nText length (words):")
    print(f"  Min: {df['text_words'].min():,}")
    print(f"  Max: {df['text_words'].max():,}")
    print(f"  Mean: {df['text_words'].mean():,.0f}")
    print(f"  Median: {df['text_words'].median():,.0f}")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].hist(df['text_words'], bins=50, color='#3498db', alpha=0.7, edgecolor='black')
    axes[0].axvline(df['text_words'].median(), color='red', linestyle='--', label=f"Median: {df['text_words'].median():.0f}")
    axes[0].set_title('Text Length Distribution (Words)', fontsize=12)
    axes[0].set_xlabel('Number of Words')
    axes[0].set_ylabel('Frequency')
    axes[0].legend()

    axes[1].hist(df['text_length'], bins=50, color='#e67e22', alpha=0.7, edgecolor='black')
    axes[1].axvline(df['text_length'].median(), color='red', linestyle='--', label=f"Median: {df['text_length'].median():.0f}")
    axes[1].set_title('Text Length Distribution (Characters)', fontsize=12)
    axes[1].set_xlabel('Number of Characters')
    axes[1].set_ylabel('Frequency')
    axes[1].legend()

    plt.tight_layout()
    plt.savefig('text_length_distributions.png', dpi=150)
    plt.show()

    print("\nSample text (first 500 chars):")
    print(df['text'].iloc[0][:500] + "...")

    duplicate_count = df.duplicated().sum()
    print(f"Duplicate rows: {duplicate_count}")

    print(f"""
    Dataset Size: {len(df):,} samples
    Classes: {class_counts.index.tolist()}
    Class Distribution: No Fit: {class_counts.get('No Fit', 0)}, Potential Fit: {class_counts.get('Potential Fit', 0)}, Good Fit: {class_counts.get('Good Fit', 0)}
    Missing Values: None
    Average Text Length: {df['text_length'].mean():.0f} characters ({df['text_words'].mean():.0f} words)
    Duplicates: {duplicate_count}

    RECOMMENDATIONS:
    1. No missing values to handle
    2. Class imbalance exists - use stratification in train/test split
    3. Text length varies - ensure model can handle long sequences
    4. Data is ordered by label - shuffle before splitting
    """)

    return df

# ============================================================
# SYNONYM MAP AND SUPPORT FUNCTIONS
# ============================================================

SYNONYM_TO_CANONICAL = {
    'j2se': 'java', 'java se': 'java', 'java standard edition': 'java', 'core java': 'java',
    'py': 'python', 'python3': 'python', 'python 3': 'python', 'cpython': 'python',
    'js': 'javascript', 'ecmascript': 'javascript', 'es6': 'javascript', 'nodejs': 'javascript',
    'node': 'javascript', 'deno': 'javascript', 'bun': 'javascript', 'ts': 'typescript',
    'cpp': 'c++', 'c plus plus': 'c++', 'cxx': 'c++', 'c sharp': 'c#', 'csharp': 'c#',
    'dotnet': 'c#', 'ror': 'ruby', 'rails': 'ruby', 'ruby on rails': 'ruby',
    'laravel': 'php', 'codeigniter': 'php', 'symfony': 'php', 'wordpress': 'php',
    'swiftui': 'swift', 'apple swift': 'swift', 'kt': 'kotlin', 'kotlin android': 'kotlin',
    'golang': 'go', 'golang language': 'go', 'rustlang': 'rust', 'scala lang': 'scala',
    'r language': 'r', 'r programming': 'r', 'rstats': 'r', 'dart language': 'dart',
    'shell': 'bash', 'sh': 'bash', 'shell script': 'bash', 'bash script': 'bash', 'zsh': 'bash',
    'common business oriented language': 'cobol', 'commercial business oriented language': 'cobol',
    'formula translating system': 'fortran', 'list processing': 'lisp', 'common lisp': 'lisp',
    'scheme': 'lisp', 'racket': 'lisp', 'clojure': 'lisp', 'smalltalk 80': 'smalltalk',
    'squeak': 'smalltalk', 'pharo': 'smalltalk', 'object pascal': 'pascal', 'delphi': 'pascal',
    'amazon web services': 'aws', 'amazon cloud': 'aws', 'aws cloud': 'aws',
    'amazon ec2': 'ec2', 'elastic compute cloud': 'ec2', 'amazon s3': 's3',
    'simple storage service': 's3', 'aws lambda': 'lambda', 'serverless lambda': 'lambda',
    'microsoft azure': 'azure', 'azure cloud': 'azure', 'ms azure': 'azure',
    'google cloud': 'gcp', 'google cloud platform': 'gcp',
    'docker container': 'docker', 'docker engine': 'docker', 'dockerfile': 'docker',
    'k8s': 'kubernetes', 'kube': 'kubernetes', 'kubectl': 'kubernetes',
    'eks': 'kubernetes', 'aks': 'kubernetes', 'gke': 'kubernetes',
    'openshift': 'kubernetes', 'container orchestration': 'kubernetes',
    'jenkins ci': 'jenkins', 'jenkins pipeline': 'jenkins', 'jenkinsfile': 'jenkins',
    'tf': 'terraform', 'hashicorp terraform': 'terraform',
    'ansible automation': 'ansible', 'ansible playbook': 'ansible',
    'git scm': 'git', 'git version control': 'git', 'source control': 'git',
    'gh': 'github', 'github actions': 'github', 'github copilot': 'github',
    'gitlab ci': 'gitlab', 'gitlab pipeline': 'gitlab', 'gitlab runner': 'gitlab',
    'argo cd': 'argo', 'argo rollouts': 'argo', 'gitops': 'argo',
    'prometheus monitoring': 'prometheus', 'metrics': 'prometheus', 'monitoring': 'prometheus',
    'grafana dashboard': 'grafana', 'visualization': 'grafana', 'observability': 'grafana',
    'elasticsearch': 'elk', 'logstash': 'elk', 'kibana': 'elk', 'elastic stack': 'elk',
    'sre': 'devops', 'site reliability engineering': 'devops', 'site reliability': 'devops',
    'devsecops': 'devops', 'mlops': 'devops', 'aiops': 'devops',
    'mysql db': 'mysql', 'maria db': 'mysql', 'mariadb': 'mysql', 'percona': 'mysql',
    'postgres': 'postgresql', 'psql': 'postgresql', 'pg': 'postgresql',
    'mongo': 'mongodb', 'nosql': 'mongodb', 'no sql': 'mongodb', 'document db': 'mongodb',
    'mongodb atlas': 'mongodb', 'redis cache': 'redis', 'in-memory db': 'redis',
    'es': 'elasticsearch', 'elastic': 'elasticsearch', 'cassandra db': 'cassandra',
    'apache spark': 'spark', 'pyspark': 'spark', 'spark sql': 'spark',
    'hdfs': 'hadoop', 'apache hadoop': 'hadoop', 'yarn': 'hadoop', 'mapreduce': 'hadoop',
    'apache kafka': 'kafka', 'confluent kafka': 'kafka', 'kafka streams': 'kafka',
    'apache airflow': 'airflow', 'airflow pipeline': 'airflow', 'dag': 'airflow',
    'snowflake db': 'snowflake', 'snowflake data cloud': 'snowflake',
    'databricks lakehouse': 'databricks', 'dbx': 'databricks', 'delta lake': 'databricks',
    'aws dynamodb': 'dynamodb', 'key-value store': 'dynamodb',
    'google bigquery': 'bigquery', 'gcp bigquery': 'bigquery',
    'aws redshift': 'redshift', 'amazon redshift': 'redshift', 'data warehouse': 'redshift',
    'etl': 'etl', 'extract transform load': 'etl', 'elt': 'etl', 'data pipeline': 'etl',
    'ml': 'machine learning', 'ml engineer': 'machine learning', 'ml model': 'machine learning',
    'dl': 'deep learning', 'deep neural network': 'deep learning', 'dnn': 'deep learning',
    'nlp': 'nlp', 'natural language understanding': 'nlp', 'nlu': 'nlp', 'text mining': 'nlp',
    'cv': 'computer vision', 'vision ai': 'computer vision', 'image recognition': 'computer vision',
    'llm': 'llm', 'large language model': 'llm', 'foundation model': 'llm',
    'gpt': 'llm', 'bert': 'llm', 'llama': 'llm', 'gemini': 'llm', 'claude': 'llm', 'mistral': 'llm',
    'retrieval augmented generation': 'rag', 'retrieval-augmented generation': 'rag', 'vector search': 'rag',
    'transformer model': 'transformers', 'attention model': 'transformers', 'self-attention': 'transformers',
    'convolutional neural network': 'cnn', 'convnet': 'cnn',
    'recurrent neural network': 'rnn', 'lstm': 'rnn', 'gru': 'rnn',
    'bidirectional encoder': 'bert', 'bert model': 'bert', 'roberta': 'bert', 'distilbert': 'bert',
    'generative pre-trained transformer': 'gpt', 'gpt-3': 'gpt', 'gpt-4': 'gpt', 'openai gpt': 'gpt',
    'chatgpt': 'gpt', 'tf': 'tensorflow', 'tensorflow 2': 'tensorflow', 'tf2': 'tensorflow',
    'torch': 'pytorch', 'pytorch lightning': 'pytorch',
    'sklearn': 'scikit-learn', 'scikit': 'scikit-learn',
    'pandas python': 'pandas', 'pd': 'pandas', 'pandas dataframe': 'pandas',
    'np': 'numpy', 'num py': 'numpy', 'numpy array': 'numpy',
    'jupyter notebook': 'jupyter', 'ipynb': 'jupyter', 'jupyter lab': 'jupyter',
    'colab': 'jupyter', 'google colab': 'jupyter',
    'huggingface': 'huggingface', 'hf': 'huggingface', 'hugging face': 'huggingface',
    'genai': 'genai', 'generative ai': 'genai', 'generative artificial intelligence': 'genai',
    'prompt design': 'prompt engineering', 'llm prompting': 'prompt engineering',
    'mpl': 'matplotlib', 'plt': 'matplotlib', 'pyplot': 'matplotlib',
    'sns': 'seaborn', 'seaborn plot': 'seaborn',
    'kaggle dataset': 'kaggle', 'kaggle competition': 'kaggle', 'kaggle notebook': 'kaggle',
    'pm': 'product manager', 'product management': 'product manager', 'technical product manager': 'product manager',
    'tpm': 'product manager', 'product owner': 'product manager',
    'program manager': 'project manager', 'pgm': 'project manager',
    'agile scrum': 'scrum master', 'scrum facilitator': 'scrum master', 'agile coach': 'scrum master',
    'agile methodology': 'agile', 'agile development': 'agile', 'safe': 'agile', 'xp': 'agile',
    'kanban board': 'kanban', 'kanban methodology': 'kanban',
    'objectives and key results': 'okr', 'okr framework': 'okr', 'quarterly goals': 'okr',
    'key performance indicator': 'kpi', 'key metric': 'kpi', 'performance metric': 'kpi',
    '6 sigma': 'six sigma', 'lean six sigma': 'six sigma',
    'lean management': 'lean', 'lean enterprise': 'lean', 'lean thinking': 'lean', 'lean manufacturing': 'lean',
    'waterfall methodology': 'waterfall', 'traditional development': 'waterfall',
    'business analyst': 'ba', 'business analysis': 'ba', 'requirements gathering': 'ba',
    'return on investment': 'roi', 'return of investment': 'roi',
    'profit and loss': 'p&l', 'income statement': 'p&l',
    'capital expenditure': 'capex', 'capital investment': 'capex',
    'operational expenditure': 'opex', 'operating expense': 'opex',
    'mergers and acquisitions': 'm&a', 'acquisitions': 'm&a', 'mergers': 'm&a', 'due diligence': 'm&a',
    'initial public offering': 'ipo', 'public offering': 'ipo',
    'private equity firm': 'pe', 'pe investment': 'pe',
    'venture capitalist': 'vc', 'vc funding': 'vc',
    'regulatory compliance': 'compliance', 'legal compliance': 'compliance', 'audit': 'compliance',
    'risk assessment': 'risk management', 'risk mitigation': 'risk management', 'risk framework': 'risk management',
    'corporate governance': 'governance', 'it governance': 'governance', 'data governance': 'governance', 'itil': 'governance',
    'organizational change': 'change management', 'transformation': 'change management',
    'led': 'leadership', 'lead': 'leadership', 'head': 'leadership', 'direct': 'leadership', 'oversee': 'leadership',
    'communicate': 'communication', 'written communication': 'communication', 'verbal communication': 'communication',
    'analytical': 'problem solving', 'critical thinking': 'problem solving', 'troubleshooting': 'problem solving',
    'collaborate': 'collaboration', 'teamwork': 'collaboration', 'cross-functional': 'collaboration',
    'adapt': 'adaptability', 'flexible': 'adaptability', 'resilient': 'adaptability',
    'prioritization': 'time management', 'deadline': 'time management', 'time tracking': 'time management',
    'negotiate': 'negotiation', 'vendor negotiation': 'negotiation', 'contract negotiation': 'negotiation',
    'eq': 'emotional intelligence', 'empathy': 'emotional intelligence', 'self-awareness': 'emotional intelligence',
    'strategic planning': 'strategic thinking', 'long-term strategy': 'strategic thinking', 'vision': 'strategic thinking',
    'innovative': 'innovation', 'creative': 'innovation', 'disruptive': 'innovation', 'design thinking': 'innovation',
    'customer centric': 'customer focus', 'user experience': 'customer focus', 'ux': 'customer focus',
    'bachelor of science': 'bachelor', 'bs': 'bachelor', 'btech': 'bachelor', 'be': 'bachelor',
    'master of science': 'master', 'ms': 'master', 'mtech': 'master', 'me': 'master',
    'doctorate': 'phd', 'doctoral': 'phd', 'dphil': 'phd', 'dsc': 'phd',
    'master of business administration': 'mba',
    'aws certification': 'aws certified', 'aws cloud practitioner': 'aws certified', 'aws solutions architect': 'aws certified',
    'project management professional': 'pmp', 'pm certification': 'pmp',
    'chartered financial analyst': 'cfa', 'certified public accountant': 'cpa',
    'scrum master': 'scrum certified', 'psm': 'scrum certified', 'csm': 'scrum certified',
    'it service management': 'itil', 'itil foundation': 'itil', 'itil certified': 'itil',
    'certified information security manager': 'cism', 'security management': 'cism',
    'certified information systems security professional': 'cissp', 'security certification': 'cissp',
    'certified ethical hacker': 'ceh', 'ethical hacking certification': 'ceh',
    'offensive security certified professional': 'oscp', 'penetration testing': 'oscp',
    'network firewall': 'firewall', 'next-gen firewall': 'firewall', 'ngfw': 'firewall',
    'virtual private network': 'vpn', 'vpn tunnel': 'vpn', 'site-to-site vpn': 'vpn',
    'intrusion detection system': 'ids', 'network ids': 'ids', 'host ids': 'ids',
    'intrusion prevention system': 'ips', 'network ips': 'ips', 'host ips': 'ips',
    'security information event management': 'siem', 'splunk': 'siem', 'qradar': 'siem',
    'security operations center': 'soc', 'soc team': 'soc', 'security monitoring': 'soc',
    'identity and access management': 'iam', 'access control': 'iam', 'privileged access': 'iam', 'pam': 'iam',
    'multi factor authentication': 'mfa', 'two factor authentication': 'mfa', '2fa': 'mfa', 'authenticator': 'mfa',
    'single sign-on': 'sso', 'saml': 'sso', 'oidc': 'sso', 'oauth': 'sso',
    'domain name system': 'dns', 'dns server': 'dns', 'dns resolution': 'dns',
    'secure sockets layer': 'ssl', 'tls': 'ssl', 'transport layer security': 'ssl', 'https': 'ssl', 'certificate': 'ssl',
    'public key infrastructure': 'pki', 'digital certificate': 'pki', 'ca': 'pki', 'certificate authority': 'pki',
    'extended detection response': 'xdr', 'endpoint detection': 'xdr', 'edr': 'xdr',
    'data loss prevention': 'dlp', 'data leakage prevention': 'dlp',
    'cloud access security broker': 'casb', 'cloud security': 'casb',
    'zero trust architecture': 'zero trust', 'zta': 'zero trust', 'never trust always verify': 'zero trust',
    'general data protection regulation': 'gdpr', 'eu privacy law': 'gdpr', 'data protection regulation': 'gdpr', 'dsgvo': 'gdpr',
    'california consumer privacy act': 'ccpa', 'cpra': 'ccpa', 'california privacy law': 'ccpa',
    'intellectual property': 'ip', 'copyright': 'ip', 'trademark': 'ip', 'patent': 'ip', 'trade secret': 'ip',
    'non-disclosure agreement': 'nda', 'confidentiality agreement': 'nda', 'non-disclosure': 'nda',
    'master services agreement': 'msa', 'services agreement': 'msa',
    'statement of work': 'sow', 'scope of work': 'sow', 'work order': 'sow',
    'end user license agreement': 'eula', 'software license': 'eula', 'license agreement': 'eula',
    'health insurance portability accountability act': 'hipaa', 'healthcare privacy': 'hipaa', 'medical data': 'hipaa',
    'soc 2': 'soc2', 'security controls': 'soc2', 'audit report': 'soc2', 'data security': 'soc2',
    'iso 27001': 'iso27001', 'information security management': 'iso27001', 'isms': 'iso27001',
    'service level agreement': 'sla', 'service level': 'sla', 'sla metrics': 'sla',
    'terms of service': 'tos', 'terms and conditions': 'tos', 'terms of use': 'tos',
    'search engine optimization': 'seo', 'organic search': 'seo', 'on-page seo': 'seo', 'off-page seo': 'seo',
    'search engine marketing': 'sem', 'paid search': 'sem',
    'pay per click': 'ppc', 'google ads': 'ppc', 'adwords': 'ppc', 'bing ads': 'ppc',
    'click through rate': 'ctr', 'click rate': 'ctr',
    'cost per acquisition': 'cpa', 'customer acquisition cost': 'cpa', 'cac': 'cpa',
    'return on ad spend': 'roas',
    'customer relationship management': 'crm', 'salesforce': 'crm', 'hubspot': 'crm', 'zoho': 'crm', 'pipedrive': 'crm',
    'email campaign': 'email marketing', 'newsletter': 'email marketing', 'marketing automation': 'email marketing',
    'smm': 'social media', 'social media marketing': 'social media', 'instagram': 'social media',
    'linkedin': 'social media', 'twitter': 'social media', 'facebook': 'social media', 'tiktok': 'social media',
    'content strategy': 'content marketing', 'blogging': 'content marketing', 'thought leadership': 'content marketing',
    'growth marketing': 'growth hacking', 'growth strategies': 'growth hacking', 'experimentation': 'growth hacking',
    'brand awareness': 'branding', 'brand identity': 'branding', 'brand strategy': 'branding',
    'lead gen': 'lead generation', 'prospecting': 'lead generation', 'outreach': 'lead generation',
    'business to business': 'b2b', 'enterprise sales': 'b2b',
    'business to consumer': 'b2c', 'consumer sales': 'b2c',
    'stock keeping unit': 'sku', 'product code': 'sku', 'inventory code': 'sku', 'upc': 'sku',
    'bill of materials': 'bom', 'material list': 'bom', 'parts list': 'bom',
    'warehouse management system': 'wms', 'transportation management system': 'tms',
    'enterprise resource planning': 'erp', 'sap': 'erp', 'oracle': 'erp', 'microsoft dynamics': 'erp', 'infor': 'erp',
    'just-in-time': 'jit', 'third-party logistics': '3pl', 'fourth party logistics': '4pl',
    'e-commerce': 'ecommerce', 'online retail': 'ecommerce', 'digital commerce': 'ecommerce',
    'shopify': 'ecommerce', 'magento': 'ecommerce', 'woocommerce': 'ecommerce', 'bigcommerce': 'ecommerce',
    'direct to consumer': 'd2c', 'dtc': 'd2c', 'direct-to-consumer': 'd2c',
    'omnichannel': 'omni channel', 'multichannel': 'omni channel', 'cross-channel': 'omni channel',
    'inventory control': 'inventory management', 'stock management': 'inventory management',
    'demand forecasting': 'demand planning', 'forecasting': 'demand planning', 'sales forecast': 'demand planning',
    'purchasing': 'procurement', 'sourcing': 'procurement', 'strategic sourcing': 'procurement',
    'transportation': 'logistics', 'shipping': 'logistics', 'fulfillment': 'logistics', 'warehousing': 'logistics',
    'dev': 'developer', 'software developer': 'developer', 'software engineer': 'developer',
    'engineer': 'developer', 'programmer': 'developer', 'coder': 'developer',
    'full stack developer': 'developer', 'backend developer': 'developer', 'frontend developer': 'developer',
    'web developer': 'developer', 'mobile developer': 'developer', 'ios developer': 'developer', 'android developer': 'developer',
    'data science': 'data scientist', 'ds': 'data scientist', 'ai scientist': 'data scientist',
    'de': 'data engineer', 'data infrastructure': 'data engineer', 'data pipeline engineer': 'data engineer',
    'devops engineer': 'devops', 'site reliability engineer': 'devops', 'sre': 'devops', 'cloud engineer': 'devops',
    'quality assurance': 'qa', 'qa engineer': 'qa', 'software tester': 'qa', 'test engineer': 'qa', 'qa analyst': 'qa', 'sdet': 'qa',
    'technical product manager': 'product', 'product analyst': 'product',
    'marketing manager': 'marketing', 'digital marketing': 'marketing', 'growth marketing': 'marketing', 'marketing director': 'marketing',
    'financial analyst': 'finance', 'financial manager': 'finance', 'finance manager': 'finance', 'controller': 'finance', 'cfo': 'finance',
    'sales manager': 'sales', 'sales director': 'sales', 'account executive': 'sales', 'business development': 'sales', 'bd': 'sales',
    'human resources': 'hr', 'hr manager': 'hr', 'talent acquisition': 'hr', 'recruiting': 'hr', 'people ops': 'hr',
    'management consultant': 'consultant', 'strategy consultant': 'consultant', 'advisory': 'consultant', 'sme': 'consultant',
    'us': 'usa', 'united states': 'usa', 'america': 'usa', 'americas': 'usa',
    'united kingdom': 'uk', 'britain': 'uk', 'england': 'uk', 'gb': 'uk', 'great britain': 'uk',
    'european union': 'eu', 'europe': 'eu', 'european': 'eu',
    'asia pacific': 'apac', 'asia-pacific': 'apac', 'asia pacific region': 'apac',
    'europe middle east africa': 'emea', 'emea region': 'emea',
    'latin america': 'latam', 'south america': 'latam', 'central america': 'latam', 'caribbean': 'latam',
    'middle east north africa': 'mena', 'mena region': 'mena',
    'gulf cooperation council': 'gcc', 'middle east gcc': 'gcc',
    'worldwide': 'ww', 'global': 'ww', 'international': 'ww', 'global operations': 'ww',
    'north america': 'north america', 'na': 'north america', 'us and canada': 'north america',
    'sa': 'south america', 'european region': 'europe', 'asian countries': 'asia', 'africa': 'africa'
}

def replace_synonyms(text: str) -> str:
    if not text:
        return ""
    text_lower = text.lower()
    sorted_synonyms = sorted(SYNONYM_TO_CANONICAL.keys(), key=len, reverse=True)
    for synonym in sorted_synonyms:
        if synonym in text_lower:
            pattern = r'\b' + re.escape(synonym) + r'\b'
            text_lower = re.sub(pattern, SYNONYM_TO_CANONICAL[synonym], text_lower)
    return text_lower

def clean_text(text: str) -> str:
    if not text:
        return ""
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = replace_synonyms(text)
    return text

def extract_pdf_text(pdf_file):
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    return text.strip()

def extract_keywords(text: str, top_n: int = 20) -> list:
    stop_words = {
        'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from',
        'has', 'he', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the',
        'to', 'was', 'were', 'will', 'with', 'i', 'you', 'we', 'they',
        'this', 'that', 'these', 'those', 'am', 'do', 'does', 'did',
        'have', 'had', 'having', 'been', 'being', 'would', 'could',
        'should', 'might', 'must', 'my', 'your', 'his', 'her', 'our',
        'their', 'me', 'him', 'us', 'them'
    }
    words = clean_text(text).split()
    keywords = []
    for w in words:
        if w not in stop_words and (len(w) > 2 or w.isdigit()):
            keywords.append(w)
    freq = Counter(keywords)
    return [word for word, _ in freq.most_common(top_n)]

def skill_gap_analysis(jd_text: str, resume_text: str):
    jd_keywords = set(extract_keywords(jd_text, top_n=30))
    resume_keywords = set(extract_keywords(resume_text, top_n=30))
    present = list(resume_keywords.intersection(jd_keywords))
    missing = list(jd_keywords.difference(resume_keywords))
    return present, missing

print("Support function loaded")

# ============================================================
# RESUME JD MATCHER CLASS
# ============================================================

class ResumeJDMatcher:
    def __init__(self):
        self.model = None
        self.resume_embeddings = None
        self.resume_texts = None

    def load_model(self):
        self.model = SentenceTransformer('all-mpnet-base-v2')
        print("Model loaded.")
        return self.model

    def encode(self, texts):
        if isinstance(texts, str):
            texts = [texts]
        return self.model.encode(texts, convert_to_numpy=True)

    def compute_similarity(self, emb1, emb2):
        from numpy.linalg import norm
        return float(np.dot(emb1, emb2) / (norm(emb1) * norm(emb2)))

    def save_embeddings(self, resume_texts, filepath="resume_embeddings.pkl"):
        if self.model is None:
            self.load_model()
        self.resume_texts = resume_texts
        self.resume_embeddings = self.encode(resume_texts)
        with open(filepath, 'wb') as f:
            pickle.dump({'texts': resume_texts, 'embeddings': self.resume_embeddings}, f)
        print(f"Saved {len(resume_texts)} resume embeddings.")

    def load_embeddings(self, filepath="resume_embeddings.pkl"):
        if os.path.exists(filepath):
            with open(filepath, 'rb') as f:
                data = pickle.load(f)
            self.resume_texts = data['texts']
            self.resume_embeddings = data['embeddings']
            print(f"Loaded {len(self.resume_texts)} resume embeddings.")
            return True
        return False

    def match_jd(self, jd_text, top_k=5):
        if self.model is None:
            self.load_model()
        if self.resume_embeddings is None:
            raise ValueError("No resume embeddings loaded. Run save_embeddings() first.")
        jd_embedding = self.encode(jd_text)[0]
        similarities = []
        for i, resume_emb in enumerate(self.resume_embeddings):
            score = self.compute_similarity(jd_embedding, resume_emb)
            similarities.append((i, score))
        similarities.sort(key=lambda x: x[1], reverse=True)
        results = []
        for idx, score in similarities[:top_k]:
            results.append({
                'rank': len(results) + 1,
                'match_score': round(score * 100, 2),
                'resume_preview': self.resume_texts[idx][:200] + "..."
            })
        return results

print("Model class loaded")

# ============================================================
# COLAB-ONLY CODE (EDA + TRAINING - Does NOT run on Streamlit)
# ============================================================

if __name__ == "__main__":

    # ===== EDA =====
    df = run_eda()

    # ===== BASELINE MODEL: TF-IDF (Full Dataset) =====
    print("\n" + "="*60)
    print("BASELINE MODEL: TF-IDF + Logistic Regression (Full)")
    print("="*60)

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"Dataset size: {len(df)} samples")
    print(f"Available columns: {df.columns.tolist()}")

    df['clean_text'] = df['text'].apply(clean_text)
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X = vectorizer.fit_transform(df['clean_text'])
    y = df['label']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    baseline_model = LogisticRegression(max_iter=1000)
    baseline_model.fit(X_train, y_train)
    y_pred = baseline_model.predict(X_test)
    baseline_accuracy = accuracy_score(y_test, y_pred)

    print(f"\nBaseline Accuracy: {baseline_accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    # ===== BASELINE MODEL: TF-IDF (500 samples) =====
    print("\n" + "="*60)
    print("BASELINE MODEL: TF-IDF + Logistic Regression (500 samples)")
    print("="*60)

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"Dataset size: {len(df)} samples")
    print(f"Available columns: {df.columns.tolist()}")

    SAMPLE_SIZE = 500
    sample_df = df.sample(n=SAMPLE_SIZE, random_state=42)
    print(f"\nUsing {len(sample_df)} samples")

    sample_df['clean_text'] = sample_df['text'].apply(clean_text)
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X = vectorizer.fit_transform(sample_df['clean_text'])
    y = sample_df['label']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    baseline_model = LogisticRegression(max_iter=1000)
    baseline_model.fit(X_train, y_train)
    y_pred = baseline_model.predict(X_test)
    baseline_accuracy = accuracy_score(y_test, y_pred)

    print(f"\nBaseline Accuracy: {baseline_accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    # ===== SBERT MODEL (Full Dataset) =====
    print("\n" + "="*60)
    print("SBERT MODEL (Full Dataset)")
    print("="*60)

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"Dataset size: {len(df)} samples")

    df = shuffle(df, random_state=42).reset_index(drop=True)

    def parse_jd_resume(text):
        jd_pattern = r'For the given job description <<(.*?)>> the resume:'
        resume_pattern = r'the resume: <<(.*?)>>\. The result is,'
        jd_match = re.search(jd_pattern, text, re.DOTALL)
        resume_match = re.search(resume_pattern, text, re.DOTALL)
        jd = jd_match.group(1).strip() if jd_match else ""
        resume = resume_match.group(1).strip() if resume_match else ""
        return jd, resume

    start_time = time.time()
    df['jd'], df['resume'] = zip(*df['text'].apply(parse_jd_resume))
    print(f"Parsing completed in {time.time() - start_time:.2f} seconds")

    jds = df['jd'].tolist()
    resumes = df['resume'].tolist()
    labels = df['label'].tolist()

    print(f"Total JD entries: {len(jds)}")
    print(f"Total Resume entries: {len(resumes)}")
    print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

    start_time = time.time()
    model = SentenceTransformer('all-mpnet-base-v2')
    print(f"Model loaded in {time.time() - start_time:.2f} seconds")

    start_time = time.time()
    jd_embeddings = model.encode(jds, convert_to_numpy=True, show_progress_bar=True)
    resume_embeddings = model.encode(resumes, convert_to_numpy=True, show_progress_bar=True)
    print(f"Embeddings created in {time.time() - start_time:.2f} seconds")

    print(f"JD embeddings shape: {jd_embeddings.shape}")
    print(f"Resume embeddings shape: {resume_embeddings.shape}")

    sbert_scores = []
    for i in range(len(jds)):
        sim = np.dot(jd_embeddings[i], resume_embeddings[i]) / (norm(jd_embeddings[i]) * norm(resume_embeddings[i]))
        sbert_scores.append(sim * 100)

    print(f"SBERT Average Match Score: {np.mean(sbert_scores):.2f}%")
    print(f"Score Range: {min(sbert_scores):.2f}% - {max(sbert_scores):.2f}%")

    concat_embeddings = np.concatenate([jd_embeddings, resume_embeddings], axis=1)
    print(f"Concatenated embeddings shape: {concat_embeddings.shape}")

    X_train, X_test, y_train, y_test = train_test_split(concat_embeddings, labels, test_size=0.2, random_state=42, stratify=labels)
    print(f"Training samples: {len(X_train)}")
    print(f"Test samples: {len(X_test)}")

    print("\nTraining Logistic Regression...")
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    sbert_acc = accuracy_score(y_test, y_pred)

    print(f"SBERT Classification Accuracy: {sbert_acc:.2%}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    # ===== SBERT MODEL (500 samples) =====
    print("\n" + "="*60)
    print("SBERT MODEL (500 samples)")
    print("="*60)

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"Dataset size: {len(df)} samples")

    df = shuffle(df, random_state=42).reset_index(drop=True)
    sample_df = df.sample(n=500, random_state=42)

    def parse_jd_resume(text):
        jd_pattern = r'For the given job description <<(.*?)>> the resume:'
        resume_pattern = r'the resume: <<(.*?)>>\. The result is,'
        jd_match = re.search(jd_pattern, text, re.DOTALL)
        resume_match = re.search(resume_pattern, text, re.DOTALL)
        jd = jd_match.group(1).strip() if jd_match else ""
        resume = resume_match.group(1).strip() if resume_match else ""
        return jd, resume

    print("\nParsing JD and Resume...")
    start_time = time.time()
    sample_df['jd'], sample_df['resume'] = zip(*sample_df['text'].apply(parse_jd_resume))
    print(f"Parsing completed in {time.time() - start_time:.2f} seconds")

    jds = sample_df['jd'].tolist()
    resumes = sample_df['resume'].tolist()
    labels = sample_df['label'].tolist()

    print(f"\nTotal JD entries: {len(jds)}")
    print(f"Total Resume entries: {len(resumes)}")
    print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

    start_time = time.time()
    model = SentenceTransformer('all-mpnet-base-v2')
    print(f"Model loaded in {time.time() - start_time:.2f} seconds")

    start_time = time.time()
    jd_embeddings = model.encode(jds, convert_to_numpy=True, show_progress_bar=True)
    resume_embeddings = model.encode(resumes, convert_to_numpy=True, show_progress_bar=True)
    print(f"Embeddings created in {time.time() - start_time:.2f} seconds")

    print(f"JD embeddings shape: {jd_embeddings.shape}")
    print(f"Resume embeddings shape: {resume_embeddings.shape}")

    sbert_scores = []
    for i in range(len(jds)):
        sim = np.dot(jd_embeddings[i], resume_embeddings[i]) / (norm(jd_embeddings[i]) * norm(resume_embeddings[i]))
        sbert_scores.append(sim * 100)

    print(f"SBERT Average Match Score: {np.mean(sbert_scores):.2f}%")
    print(f"Score Range: {min(sbert_scores):.2f}% - {max(sbert_scores):.2f}%")

    concat_embeddings = np.concatenate([jd_embeddings, resume_embeddings], axis=1)
    print(f"Concatenated embeddings shape: {concat_embeddings.shape}")

    X_train, X_test, y_train, y_test = train_test_split(concat_embeddings, labels, test_size=0.2, random_state=42, stratify=labels)
    print(f"Training samples: {len(X_train)}")
    print(f"Test samples: {len(X_test)}")

    print("\nTraining Logistic Regression...")
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    sbert_acc = accuracy_score(y_test, y_pred)

    print(f"SBERT Classification Accuracy: {sbert_acc:.2%}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\n" + "="*60)
    print("✅ Colab execution complete!")
    print("="*60)

# ============================================================
# STREAMLIT APP CODE (Runs on Streamlit)
# ============================================================

st.set_page_config(
    page_title="Resume-JD Matcher",
    layout="wide"
)

st.title("Resume - Job Description Matcher")
st.write("Upload a resume (PDF) and paste a job description to calculate a match score.")

if 'matcher' not in st.session_state:
    with st.spinner("Loading model..."):
        st.session_state.matcher = ResumeJDMatcher()
        st.session_state.matcher.load_model()
        st.session_state.match_score = None

with st.sidebar:
    st.subheader("Input")
    jd_text = st.text_area(
        "Job Description",
        height=200,
        placeholder="Paste job description here..."
    )
    uploaded_file = st.file_uploader(
        "Upload Resume (PDF)",
        type=["pdf"]
    )
    process_button = st.button("Process and Match")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Job Description Preview")
    if jd_text:
        st.text_area("", jd_text[:500] + ("..." if len(jd_text) > 500 else ""), height=150, disabled=True)
    else:
        st.info("Paste a job description in the sidebar")

with col2:
    st.subheader("Resume Uploaded")
    if uploaded_file:
        st.success("File uploaded: " + uploaded_file.name)
    else:
        st.info("Upload a PDF resume in the sidebar")

if process_button:
    if not jd_text:
        st.error("Please paste a job description")
    elif not uploaded_file:
        st.error("Please upload a resume")
    else:
        with st.spinner("Processing..."):
            resume_text = extract_pdf_text(uploaded_file)
            if not resume_text:
                st.error("Could not extract text from PDF. Please use a text-based PDF.")
                st.stop()
            cleaned_jd = clean_text(jd_text)
            cleaned_resume = clean_text(resume_text)
            jd_embedding = st.session_state.matcher.encode(cleaned_jd)[0]
            resume_embedding = st.session_state.matcher.encode(cleaned_resume)[0]
            similarity = st.session_state.matcher.compute_similarity(jd_embedding, resume_embedding)
            match_score = similarity * 100
            present_skills, missing_skills = skill_gap_analysis(jd_text, resume_text)
            st.session_state.match_score = match_score
            st.session_state.present_skills = present_skills
            st.session_state.missing_skills = missing_skills
            st.session_state.resume_text = resume_text
            st.session_state.jd_text = jd_text

if st.session_state.get('match_score') is not None:
    st.divider()
    st.subheader("Results")
    match_score = st.session_state.match_score
    col_a, col_b, col_c = st.columns([1, 2, 1])
    with col_b:
        st.markdown(f"<h1 style='text-align: center;'>{match_score:.1f}%</h1>", unsafe_allow_html=True)
        if match_score >= 70:
            st.success("Good Fit")
        elif match_score >= 40:
            st.warning("Potential Fit")
        else:
            st.error("Not a Good Fit")
        st.progress(match_score / 100)

    st.subheader("Score Analysis")
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.barh(['Match Score'], [match_score], color='skyblue')
    ax.axvline(x=70, color='green', linestyle='--', label='Good Fit (70%)')
    ax.axvline(x=40, color='orange', linestyle='--', label='Potential Fit (40%)')
    ax.set_xlim(0, 100)
    ax.set_xlabel('Match Score (%)')
    ax.legend()
    st.pyplot(fig)

    st.subheader("Skill Gap Analysis")
    c1, c2 = st.columns(2)
    with c1:
        st.write("Present Skills")
        if st.session_state.present_skills:
            st.write(", ".join(st.session_state.present_skills[:15]))
        else:
            st.caption("No matching skills found")
    with c2:
        st.write("Missing Skills")
        if st.session_state.missing_skills:
            st.write(", ".join(st.session_state.missing_skills[:15]))
        else:
            st.caption("All key skills found")

    with st.expander("Resume Preview"):
        st.text(st.session_state.resume_text[:1500] + "..." if len(st.session_state.resume_text) > 1500 else st.session_state.resume_text)

    with st.expander("Job Description Preview"):
        st.text(st.session_state.jd_text[:1500] + "..." if len(st.session_state.jd_text) > 1500 else st.session_state.jd_text)

st.divider()
st.caption("Built with Sentence-BERT for semantic matching")