# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHnJxbcZy4-OcgccOjBn2smZYdsxh48X
"""

# -*- coding: utf-8 -*-
"""Resume-JD Matcher - Full Implementation"""

import re
import os
import pickle
import time
from collections import Counter
from typing import List, Tuple

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.utils import shuffle
from numpy.linalg import norm

from sentence_transformers import SentenceTransformer
from datasets import load_dataset
import pdfplumber


def run_eda():
    """Load and analyze the dataset."""
    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    print(f"Dataset size: {len(df)} samples")
    print(f"Columns: {df.columns.tolist()}")

    class_counts = df['label'].value_counts()
    print("Class distribution:")
    print(class_counts)

    df['text_words'] = df['text'].astype(str).str.split().str.len()
    print(f"Text length (words): Min: {df['text_words'].min()}, Max: {df['text_words'].max()}, Mean: {df['text_words'].mean():.0f}")

    duplicate_count = df.duplicated().sum()
    print(f"Duplicate rows: {duplicate_count}")
    return df


SYNONYM_TO_CANONICAL = {
    'j2se': 'java', 'java se': 'java', 'java standard edition': 'java', 'core java': 'java',
    'py': 'python', 'python3': 'python', 'python 3': 'python', 'cpython': 'python',
    'js': 'javascript', 'ecmascript': 'javascript', 'es6': 'javascript', 'nodejs': 'javascript',
    'node': 'javascript', 'deno': 'javascript', 'bun': 'javascript',
    'cpp': 'c++', 'c plus plus': 'c++', 'cxx': 'c++', 'c sharp': 'c#', 'csharp': 'c#',
    'rails': 'ruby', 'ruby on rails': 'ruby', 'ror': 'ruby',
    'laravel': 'php', 'codeigniter': 'php', 'symfony': 'php', 'wordpress': 'php',
    'golang': 'go', 'golang language': 'go',
    'amazon web services': 'aws', 'amazon cloud': 'aws', 'aws cloud': 'aws',
    'amazon ec2': 'ec2', 'elastic compute cloud': 'ec2',
    'amazon s3': 's3', 'simple storage service': 's3',
    'aws lambda': 'lambda', 'serverless lambda': 'lambda',
    'microsoft azure': 'azure', 'azure cloud': 'azure', 'ms azure': 'azure',
    'google cloud': 'gcp', 'google cloud platform': 'gcp',
    'docker container': 'docker', 'docker engine': 'docker', 'dockerfile': 'docker',
    'k8s': 'kubernetes', 'kube': 'kubernetes', 'kubectl': 'kubernetes',
    'eks': 'kubernetes', 'aks': 'kubernetes', 'gke': 'kubernetes',
    'jenkins ci': 'jenkins', 'jenkins pipeline': 'jenkins', 'jenkinsfile': 'jenkins',
    'tf': 'terraform', 'hashicorp terraform': 'terraform',
    'ansible automation': 'ansible', 'ansible playbook': 'ansible',
    'gh': 'github', 'github actions': 'github',
    'gitlab ci': 'gitlab', 'gitlab pipeline': 'gitlab', 'gitlab runner': 'gitlab',
    'argo cd': 'argo', 'argo rollouts': 'argo', 'gitops': 'argo',
    'prometheus monitoring': 'prometheus', 'metrics': 'prometheus', 'monitoring': 'prometheus',
    'grafana dashboard': 'grafana', 'visualization': 'grafana', 'observability': 'grafana',
    'elasticsearch': 'elk', 'logstash': 'elk', 'kibana': 'elk', 'elastic stack': 'elk',
    'sre': 'devops', 'site reliability engineering': 'devops', 'site reliability': 'devops',
    'mysql db': 'mysql', 'maria db': 'mysql', 'mariadb': 'mysql',
    'postgres': 'postgresql', 'psql': 'postgresql', 'pg': 'postgresql',
    'mongo': 'mongodb', 'nosql': 'mongodb', 'document db': 'mongodb',
    'mongodb atlas': 'mongodb', 'redis cache': 'redis', 'in-memory db': 'redis',
    'es': 'elasticsearch', 'elastic': 'elasticsearch',
    'apache spark': 'spark', 'pyspark': 'spark', 'spark sql': 'spark',
    'apache hadoop': 'hadoop', 'hdfs': 'hadoop',
    'apache kafka': 'kafka', 'confluent kafka': 'kafka',
    'apache airflow': 'airflow', 'airflow pipeline': 'airflow', 'dag': 'airflow',
    'snowflake db': 'snowflake', 'snowflake data cloud': 'snowflake',
    'databricks lakehouse': 'databricks', 'dbx': 'databricks', 'delta lake': 'databricks',
    'aws dynamodb': 'dynamodb', 'key-value store': 'dynamodb',
    'google bigquery': 'bigquery', 'gcp bigquery': 'bigquery',
    'aws redshift': 'redshift', 'amazon redshift': 'redshift', 'data warehouse': 'redshift',
    'etl': 'etl', 'extract transform load': 'etl', 'data pipeline': 'etl',
    'ml': 'machine learning', 'ml engineer': 'machine learning',
    'dl': 'deep learning', 'deep neural network': 'deep learning', 'dnn': 'deep learning',
    'nlp': 'nlp', 'natural language understanding': 'nlp', 'nlu': 'nlp',
    'cv': 'computer vision', 'vision ai': 'computer vision',
    'llm': 'llm', 'large language model': 'llm', 'foundation model': 'llm',
    'gpt': 'llm', 'bert': 'llm', 'llama': 'llm', 'gemini': 'llm', 'claude': 'llm',
    'retrieval augmented generation': 'rag', 'retrieval-augmented generation': 'rag',
    'transformer model': 'transformers', 'attention model': 'transformers',
    'convolutional neural network': 'cnn', 'convnet': 'cnn',
    'recurrent neural network': 'rnn', 'lstm': 'rnn', 'gru': 'rnn',
    'bert model': 'bert', 'roberta': 'bert', 'distilbert': 'bert',
    'generative pre-trained transformer': 'gpt', 'gpt-3': 'gpt', 'gpt-4': 'gpt',
    'chatgpt': 'gpt', 'tf': 'tensorflow', 'tensorflow 2': 'tensorflow',
    'torch': 'pytorch', 'pytorch lightning': 'pytorch',
    'sklearn': 'scikit-learn', 'scikit': 'scikit-learn',
    'pd': 'pandas', 'pandas dataframe': 'pandas',
    'np': 'numpy', 'num py': 'numpy', 'numpy array': 'numpy',
    'jupyter notebook': 'jupyter', 'ipynb': 'jupyter', 'jupyter lab': 'jupyter',
    'colab': 'jupyter', 'google colab': 'jupyter',
    'hf': 'huggingface', 'hugging face': 'huggingface',
    'genai': 'genai', 'generative ai': 'genai', 'generative artificial intelligence': 'genai',
    'mpl': 'matplotlib', 'plt': 'matplotlib', 'pyplot': 'matplotlib',
    'sns': 'seaborn', 'seaborn plot': 'seaborn',
    'pm': 'product manager', 'product management': 'product manager',
    'tpm': 'product manager', 'product owner': 'product manager',
    'pgm': 'project manager', 'program manager': 'project manager',
    'agile scrum': 'scrum master', 'scrum facilitator': 'scrum master',
    'agile methodology': 'agile', 'agile development': 'agile', 'safe': 'agile', 'xp': 'agile',
    'kanban board': 'kanban', 'kanban methodology': 'kanban',
    'okr framework': 'okr', 'objectives and key results': 'okr',
    'key performance indicator': 'kpi', 'key metric': 'kpi',
    'six sigma': 'six sigma', 'lean six sigma': 'six sigma',
    'lean management': 'lean', 'lean enterprise': 'lean', 'lean thinking': 'lean',
    'waterfall methodology': 'waterfall', 'traditional development': 'waterfall',
    'business analyst': 'ba', 'business analysis': 'ba',
    'return on investment': 'roi', 'return of investment': 'roi',
    'profit and loss': 'p_and_l', 'income statement': 'p_and_l',
    'capital expenditure': 'capex', 'capital investment': 'capex',
    'operational expenditure': 'opex', 'operating expense': 'opex',
    'mergers and acquisitions': 'm_and_a', 'acquisitions': 'm_and_a', 'mergers': 'm_and_a',
    'initial public offering': 'ipo', 'public offering': 'ipo',
    'private equity firm': 'pe', 'pe investment': 'pe',
    'venture capitalist': 'vc', 'vc funding': 'vc',
    'regulatory compliance': 'compliance', 'legal compliance': 'compliance', 'audit': 'compliance',
    'risk assessment': 'risk management', 'risk mitigation': 'risk management',
    'corporate governance': 'governance', 'it governance': 'governance',
    'organizational change': 'change management', 'transformation': 'change management',
    'led': 'leadership', 'lead': 'leadership', 'head': 'leadership', 'direct': 'leadership',
    'communicate': 'communication', 'written communication': 'communication',
    'analytical': 'problem solving', 'critical thinking': 'problem solving',
    'collaborate': 'collaboration', 'teamwork': 'collaboration', 'cross-functional': 'collaboration',
    'adapt': 'adaptability', 'flexible': 'adaptability', 'resilient': 'adaptability',
    'prioritization': 'time management', 'deadline': 'time management',
    'negotiate': 'negotiation', 'vendor negotiation': 'negotiation',
    'eq': 'emotional intelligence', 'empathy': 'emotional intelligence',
    'strategic planning': 'strategic thinking', 'long-term strategy': 'strategic thinking',
    'innovative': 'innovation', 'creative': 'innovation', 'design thinking': 'innovation',
    'customer centric': 'customer focus', 'user experience': 'customer focus', 'ux': 'customer focus',
    'bachelor of science': 'bachelor', 'bs': 'bachelor', 'btech': 'bachelor',
    'master of science': 'master', 'ms': 'master', 'mtech': 'master',
    'doctorate': 'phd', 'doctoral': 'phd', 'dphil': 'phd',
    'master of business administration': 'mba',
    'aws certification': 'aws certified', 'aws cloud practitioner': 'aws certified',
    'project management professional': 'pmp', 'pm certification': 'pmp',
    'chartered financial analyst': 'cfa', 'certified public accountant': 'cpa',
    'psm': 'scrum certified', 'csm': 'scrum certified', 'scrum certificate': 'scrum certified',
    'it service management': 'itil', 'itil foundation': 'itil',
    'certified information security manager': 'cism', 'security management': 'cism',
    'cissp': 'cissp', 'security certification': 'cissp',
    'certified ethical hacker': 'ceh', 'ethical hacking certification': 'ceh',
    'network firewall': 'firewall', 'next-gen firewall': 'firewall', 'ngfw': 'firewall',
    'virtual private network': 'vpn', 'vpn tunnel': 'vpn',
    'intrusion detection system': 'ids', 'network ids': 'ids',
    'intrusion prevention system': 'ips', 'network ips': 'ips',
    'security information event management': 'siem', 'splunk': 'siem',
    'security operations center': 'soc', 'soc team': 'soc',
    'identity and access management': 'iam', 'access control': 'iam', 'pam': 'iam',
    'multi factor authentication': 'mfa', 'two factor authentication': 'mfa', '2fa': 'mfa',
    'single sign-on': 'sso', 'saml': 'sso', 'oidc': 'sso', 'oauth': 'sso',
    'domain name system': 'dns', 'dns server': 'dns',
    'secure sockets layer': 'ssl', 'tls': 'ssl', 'transport layer security': 'ssl', 'https': 'ssl',
    'public key infrastructure': 'pki', 'digital certificate': 'pki',
    'extended detection response': 'xdr', 'endpoint detection': 'xdr', 'edr': 'xdr',
    'data loss prevention': 'dlp', 'data leakage prevention': 'dlp',
    'cloud access security broker': 'casb', 'cloud security': 'casb',
    'zero trust architecture': 'zero trust', 'zta': 'zero trust',
    'general data protection regulation': 'gdpr', 'eu privacy law': 'gdpr',
    'california consumer privacy act': 'ccpa', 'cpra': 'ccpa',
    'intellectual property': 'ip', 'copyright': 'ip', 'trademark': 'ip', 'patent': 'ip',
    'non-disclosure agreement': 'nda', 'confidentiality agreement': 'nda',
    'master services agreement': 'msa',
    'statement of work': 'sow', 'scope of work': 'sow',
    'end user license agreement': 'eula', 'software license': 'eula',
    'health insurance portability accountability act': 'hipaa',
    'soc 2': 'soc2', 'security controls': 'soc2',
    'iso 27001': 'iso27001', 'information security management': 'iso27001', 'isms': 'iso27001',
    'service level agreement': 'sla', 'service level': 'sla',
    'terms of service': 'tos', 'terms and conditions': 'tos',
    'search engine optimization': 'seo', 'organic search': 'seo',
    'search engine marketing': 'sem', 'paid search': 'sem',
    'pay per click': 'ppc', 'google ads': 'ppc', 'adwords': 'ppc',
    'click through rate': 'ctr', 'click rate': 'ctr',
    'cost per acquisition': 'cpa', 'customer acquisition cost': 'cpa', 'cac': 'cpa',
    'return on ad spend': 'roas',
    'customer relationship management': 'crm', 'salesforce': 'crm', 'hubspot': 'crm',
    'email marketing': 'email marketing', 'newsletter': 'email marketing',
    'social media': 'social media', 'smm': 'social media', 'linkedin': 'social media',
    'content marketing': 'content marketing', 'blogging': 'content marketing',
    'growth marketing': 'growth hacking', 'growth strategies': 'growth hacking',
    'brand awareness': 'branding', 'brand identity': 'branding',
    'lead generation': 'lead generation', 'prospecting': 'lead generation',
    'business to business': 'b2b', 'enterprise sales': 'b2b',
    'business to consumer': 'b2c', 'consumer sales': 'b2c',
    'stock keeping unit': 'sku', 'product code': 'sku',
    'bill of materials': 'bom', 'material list': 'bom',
    'warehouse management system': 'wms', 'transportation management system': 'tms',
    'enterprise resource planning': 'erp', 'sap': 'erp', 'oracle': 'erp',
    'just-in-time': 'jit', 'third-party logistics': '3pl',
    'e-commerce': 'ecommerce', 'online retail': 'ecommerce',
    'shopify': 'ecommerce', 'magento': 'ecommerce', 'woocommerce': 'ecommerce',
    'direct to consumer': 'd2c', 'dtc': 'd2c',
    'omnichannel': 'omni channel', 'multichannel': 'omni channel',
    'inventory control': 'inventory management', 'stock management': 'inventory management',
    'demand forecasting': 'demand planning', 'forecasting': 'demand planning',
    'purchasing': 'procurement', 'sourcing': 'procurement',
    'transportation': 'logistics', 'shipping': 'logistics', 'fulfillment': 'logistics',
    'dev': 'developer', 'software developer': 'developer', 'software engineer': 'developer',
    'engineer': 'developer', 'programmer': 'developer', 'coder': 'developer',
    'full stack developer': 'developer', 'backend developer': 'developer', 'frontend developer': 'developer',
    'data science': 'data scientist', 'ds': 'data scientist',
    'de': 'data engineer', 'data pipeline engineer': 'data engineer',
    'devops engineer': 'devops', 'site reliability engineer': 'devops', 'sre': 'devops',
    'quality assurance': 'qa', 'qa engineer': 'qa', 'software tester': 'qa',
    'technical product manager': 'product', 'product analyst': 'product',
    'marketing manager': 'marketing', 'digital marketing': 'marketing',
    'financial analyst': 'finance', 'financial manager': 'finance', 'controller': 'finance',
    'sales manager': 'sales', 'account executive': 'sales', 'business development': 'sales',
    'human resources': 'hr', 'hr manager': 'hr', 'talent acquisition': 'hr', 'recruiting': 'hr',
    'management consultant': 'consultant', 'strategy consultant': 'consultant',
    'us': 'usa', 'united states': 'usa', 'america': 'usa',
    'united kingdom': 'uk', 'britain': 'uk', 'england': 'uk', 'gb': 'uk',
    'european union': 'eu', 'europe': 'eu',
    'asia pacific': 'apac', 'asia-pacific': 'apac',
    'europe middle east africa': 'emea', 'emea region': 'emea',
    'latin america': 'latam', 'south america': 'latam',
    'middle east north africa': 'mena', 'mena region': 'mena',
    'gulf cooperation council': 'gcc', 'middle east gcc': 'gcc',
    'worldwide': 'ww', 'global': 'ww', 'international': 'ww',
    'north america': 'north america', 'na': 'north america'
}


def replace_synonyms(text: str) -> str:
    if not text:
        return ""
    text_lower = text.lower()
    for synonym in sorted(SYNONYM_TO_CANONICAL.keys(), key=len, reverse=True):
        if synonym in text_lower:
            text_lower = re.sub(r'\b' + re.escape(synonym) + r'\b', SYNONYM_TO_CANONICAL[synonym], text_lower)
    return text_lower


def clean_text(text: str) -> str:
    if not text:
        return ""
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return replace_synonyms(text)


def extract_pdf_text(pdf_file) -> str:
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    return text.strip()


def extract_keywords(text: str, top_n: int = 20) -> List[str]:
    stop_words = {
        'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from',
        'has', 'he', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the',
        'to', 'was', 'were', 'will', 'with', 'i', 'you', 'we', 'they',
        'this', 'that', 'these', 'those', 'am', 'do', 'does', 'did',
        'have', 'had', 'having', 'been', 'being', 'would', 'could',
        'should', 'might', 'must', 'my', 'your', 'his', 'her', 'our',
        'their', 'me', 'him', 'us', 'them'
    }
    words = clean_text(text).split()
    keywords = [w for w in words if w not in stop_words and (len(w) > 2 or w.isdigit())]
    freq = Counter(keywords)
    return [word for word, _ in freq.most_common(top_n)]


def skill_gap_analysis(jd_text: str, resume_text: str) -> Tuple[List[str], List[str]]:
    jd_keywords = set(extract_keywords(jd_text, top_n=30))
    resume_keywords = set(extract_keywords(resume_text, top_n=30))
    return list(resume_keywords.intersection(jd_keywords)), list(jd_keywords.difference(resume_keywords))


print("Support functions loaded")


class ResumeJDMatcher:
    def __init__(self):
        self.model = None
        self.resume_embeddings = None
        self.resume_texts = None

    def load_model(self):
        self.model = SentenceTransformer('all-mpnet-base-v2')
        return self.model

    def encode(self, texts):
        if isinstance(texts, str):
            texts = [texts]
        return self.model.encode(texts, convert_to_numpy=True)

    def compute_similarity(self, emb1, emb2):
        return float(np.dot(emb1, emb2) / (norm(emb1) * norm(emb2)))

    def save_embeddings(self, resume_texts, filepath="resume_embeddings.pkl"):
        if self.model is None:
            self.load_model()
        self.resume_texts = resume_texts
        self.resume_embeddings = self.encode(resume_texts)
        with open(filepath, 'wb') as f:
            pickle.dump({'texts': resume_texts, 'embeddings': self.resume_embeddings}, f)
        print(f"Saved {len(resume_texts)} resume embeddings.")

    def load_embeddings(self, filepath="resume_embeddings.pkl"):
        if os.path.exists(filepath):
            with open(filepath, 'rb') as f:
                data = pickle.load(f)
            self.resume_texts = data['texts']
            self.resume_embeddings = data['embeddings']
            return True
        return False

    def match_jd(self, jd_text, top_k=5):
        if self.model is None:
            self.load_model()
        if self.resume_embeddings is None:
            raise ValueError("No resume embeddings loaded.")
        jd_embedding = self.encode(jd_text)[0]
        similarities = [(i, self.compute_similarity(jd_embedding, emb)) for i, emb in enumerate(self.resume_embeddings)]
        similarities.sort(key=lambda x: x[1], reverse=True)
        return [{'rank': i+1, 'match_score': round(score*100, 2), 'resume_preview': self.resume_texts[idx][:200] + "..."}
                for i, (idx, score) in enumerate(similarities[:top_k])]


print("Model class loaded")


if __name__ == "__main__":
    print("Running in Colab mode")

    df = run_eda()

    print("Baseline: TF-IDF + Logistic Regression (Full Dataset)")

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    df['clean_text'] = df['text'].apply(clean_text)

    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X = vectorizer.fit_transform(df['clean_text'])
    y = df['label']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    baseline_model = LogisticRegression(max_iter=1000)
    baseline_model.fit(X_train, y_train)
    y_pred = baseline_model.predict(X_test)
    baseline_accuracy = accuracy_score(y_test, y_pred)

    print(f"Baseline Accuracy: {baseline_accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    print("Advanced: Sentence-BERT (Full Dataset)")

    dataset = load_dataset('facehuggerapoorv/resume-jd-match')
    df = pd.DataFrame(dataset['train'])
    df = shuffle(df, random_state=42).reset_index(drop=True)

    def parse_jd_resume(text):
        jd_match = re.search(r'For the given job description <<(.*?)>> the resume:', text, re.DOTALL)
        resume_match = re.search(r'the resume: <<(.*?)>>\. The result is,', text, re.DOTALL)
        return (jd_match.group(1).strip() if jd_match else "",
                resume_match.group(1).strip() if resume_match else "")

    start_time = time.time()
    df['jd'], df['resume'] = zip(*df['text'].apply(parse_jd_resume))
    print(f"Parsing completed in {time.time() - start_time:.2f} seconds")

    jds = df['jd'].tolist()
    resumes = df['resume'].tolist()
    labels = df['label'].tolist()

    print(f"Total samples: {len(jds)}")
    print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

    start_time = time.time()
    model = SentenceTransformer('all-mpnet-base-v2')
    print(f"Model loaded in {time.time() - start_time:.2f} seconds")

    start_time = time.time()
    jd_embeddings = model.encode(jds, convert_to_numpy=True)
    resume_embeddings = model.encode(resumes, convert_to_numpy=True)
    print(f"Embeddings created in {time.time() - start_time:.2f} seconds")

    sbert_scores = [
        np.dot(jd_embeddings[i], resume_embeddings[i]) / (norm(jd_embeddings[i]) * norm(resume_embeddings[i])) * 100
        for i in range(len(jds))
    ]
    print(f"SBERT Average Match Score: {np.mean(sbert_scores):.2f}%")
    print(f"Score Range: {min(sbert_scores):.2f}% - {max(sbert_scores):.2f}%")

    concat_embeddings = np.concatenate([jd_embeddings, resume_embeddings], axis=1)
    X_train, X_test, y_train, y_test = train_test_split(concat_embeddings, labels, test_size=0.2, random_state=42, stratify=labels)
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    sbert_acc = accuracy_score(y_test, y_pred)

    print(f"SBERT Classification Accuracy: {sbert_acc:.2%}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    print("Colab execution complete.")


st.set_page_config(page_title="Resume-JD Matcher", layout="wide")
st.title("Resume - Job Description Matcher")
st.write("Upload a resume (PDF) and paste a job description to calculate a match score.")

if 'matcher' not in st.session_state:
    with st.spinner("Loading model..."):
        st.session_state.matcher = ResumeJDMatcher()
        st.session_state.matcher.load_model()
        st.session_state.match_score = None

with st.sidebar:
    st.subheader("Input")
    jd_text = st.text_area("Job Description", height=200, placeholder="Paste job description here...")
    uploaded_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"])
    process_button = st.button("Process and Match")

col1, col2 = st.columns(2)
with col1:
    st.subheader("Job Description Preview")
    if jd_text:
        st.text_area("", jd_text[:500] + ("..." if len(jd_text) > 500 else ""), height=150, disabled=True)
    else:
        st.info("Paste a job description in the sidebar")

with col2:
    st.subheader("Resume Uploaded")
    if uploaded_file:
        st.success(f"File uploaded: {uploaded_file.name}")
    else:
        st.info("Upload a PDF resume in the sidebar")

if process_button:
    if not jd_text:
        st.error("Please paste a job description")
    elif not uploaded_file:
        st.error("Please upload a resume")
    else:
        with st.spinner("Processing..."):
            resume_text = extract_pdf_text(uploaded_file)
            if not resume_text:
                st.error("Could not extract text from PDF. Please use a text-based PDF.")
                st.stop()
            cleaned_jd = clean_text(jd_text)
            cleaned_resume = clean_text(resume_text)
            jd_embedding = st.session_state.matcher.encode(cleaned_jd)[0]
            resume_embedding = st.session_state.matcher.encode(cleaned_resume)[0]
            match_score = st.session_state.matcher.compute_similarity(jd_embedding, resume_embedding) * 100
            present_skills, missing_skills = skill_gap_analysis(jd_text, resume_text)
            st.session_state.match_score = match_score
            st.session_state.present_skills = present_skills
            st.session_state.missing_skills = missing_skills
            st.session_state.resume_text = resume_text
            st.session_state.jd_text = jd_text

if st.session_state.get('match_score') is not None:
    st.divider()
    st.subheader("Results")
    match_score = st.session_state.match_score
    col_a, col_b, col_c = st.columns([1, 2, 1])
    with col_b:
        st.markdown(f"<h1 style='text-align: center;'>{match_score:.1f}%</h1>", unsafe_allow_html=True)
        if match_score >= 70:
            st.success("Good Fit")
        elif match_score >= 40:
            st.warning("Potential Fit")
        else:
            st.error("Not a Good Fit")
        st.progress(match_score / 100)

    st.subheader("Score Analysis")
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.barh(['Match Score'], [match_score], color='skyblue')
    ax.axvline(x=70, color='green', linestyle='--', label='Good Fit (70%)')
    ax.axvline(x=40, color='orange', linestyle='--', label='Potential Fit (40%)')
    ax.set_xlim(0, 100)
    ax.set_xlabel('Match Score (%)')
    ax.legend()
    st.pyplot(fig)

    st.subheader("Skill Gap Analysis")
    c1, c2 = st.columns(2)
    with c1:
        st.write("Present Skills")
        if st.session_state.present_skills:
            st.write(", ".join(st.session_state.present_skills[:15]))
        else:
            st.caption("No matching skills found")
    with c2:
        st.write("Missing Skills")
        if st.session_state.missing_skills:
            st.write(", ".join(st.session_state.missing_skills[:15]))
        else:
            st.caption("All key skills found")

    with st.expander("Resume Preview"):
        st.text(st.session_state.resume_text[:1500] + ("..." if len(st.session_state.resume_text) > 1500 else ""))

    with st.expander("Job Description Preview"):
        st.text(st.session_state.jd_text[:1500] + ("..." if len(st.session_state.jd_text) > 1500 else ""))

st.divider()
st.caption("Built with Sentence-BERT for semantic matching")