# -*- coding: utf-8 -*-
"""Utilities A .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dk-pd95nJnrciOLWIUrflTUKq2XiXTgR
"""

#!pip install pdfplumber
import re
import pdfplumber
from collections import Counter
from typing import List, Tuple, Optional

#Support Functions

def clean_text(text: str) -> str:
    if not text:
        return ""# No msg has been added in order to make sure the msg does not end up in extracted words list
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def extract_pdf_text(pdf_file):# Extracting all texts from PDF
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    return text.strip()


def extract_keywords(text: str, top_n: int = 20) -> list:
    # Hardcoded stopwords from NLTK package. As Streamlit may not download NLTK package.
    stop_words = { 'a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during',
 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma',
 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some',
 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where',
 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've" }

    words = clean_text(text).split()

    keywords = []
    for w in words:
        if w not in stop_words and (len(w) > 2 or w.isdigit()):
            keywords.append(w)

    freq = Counter(keywords)

    return [word for word, _ in freq.most_common(top_n)]




def skill_gap_analysis(jd_text: str, resume_text: str): # Extraction and comparision
    jd_keywords = set(extract_keywords(jd_text, top_n=30))
    resume_keywords = set(extract_keywords(resume_text, top_n=30))
    present = list(resume_keywords.intersection(jd_keywords))
    missing = list(jd_keywords.difference(resume_keywords))
    return present, missing

print("Support function loaded")